// Text is an extract from The Canterbury Tales
// Full text at http://www.gutenberg.org/dirs/etext00/cbtls12.txt
#include <avr/pgmspace.h>

prog_char knightsTale[] PROGMEM= {
"                     THE KNIGHT'S TALE <1>\n"
"\n"
"\n"
"WHILOM*, as olde stories tellen us,                            *formerly\n"
"There was a duke that highte* Theseus.                   *was called <2>\n"
"Of Athens he was lord and governor,\n"
"And in his time such a conqueror\n"
"That greater was there none under the sun.\n"
"Full many a riche country had he won.\n"
"What with his wisdom and his chivalry,\n"
"He conquer'd all the regne of Feminie,<3>\n"
"That whilom was y-cleped Scythia;\n"
"And weddede the Queen Hippolyta\n"
"And brought her home with him to his country\n"
"With muchel* glory and great solemnity,                           *great\n"
"And eke her younge sister Emily,\n"
"And thus with vict'ry and with melody\n"
"Let I this worthy Duke to Athens ride,\n"
"And all his host, in armes him beside.\n"
"\n"
"And certes, if it n'ere* too long to hear,                     *were not\n"
"I would have told you fully the mannere,\n"
"How wonnen* was the regne of Feminie, <4>                           *won\n"
"By Theseus, and by his chivalry;\n"
"And of the greate battle for the nonce\n"
"Betwixt Athenes and the Amazons;\n"
"And how assieged was Hippolyta,\n"
"The faire hardy queen of Scythia;\n"
"And of the feast that was at her wedding\n"
"And of the tempest at her homecoming.\n"
"But all these things I must as now forbear.\n"
"I have, God wot, a large field to ear*                       *plough<5>;\n"
"And weake be the oxen in my plough;\n"
"The remnant of my tale is long enow.\n"
"I will not *letten eke none of this rout*.                *hinder any of\n"
"Let every fellow tell his tale about,                      this company*\n"
"And let see now who shall the supper win.\n"
"There *as I left*, I will again begin.                *where I left off*\n"
"\n"
"This Duke, of whom I make mentioun,\n"
"When he was come almost unto the town,\n"
"In all his weal, and in his moste pride,\n"
"He was ware, as he cast his eye aside,\n"
"Where that there kneeled in the highe way\n"
"A company of ladies, tway and tway,\n"
"Each after other, clad in clothes black:\n"
"But such a cry and such a woe they make,\n"
"That in this world n'is creature living,\n"
"That hearde such another waimenting*                      *lamenting <6>\n"
"And of this crying would they never stenten*,                    *desist\n"
"Till they the reines of his bridle henten*.                       *seize\n"
"\"What folk be ye that at mine homecoming\n"
"Perturben so my feaste with crying?\"\n"
"Quoth Theseus; \"Have ye so great envy\n"
"Of mine honour, that thus complain and cry?\n"
"Or who hath you misboden*, or offended?                         *wronged\n"
"Do telle me, if it may be amended;\n"
"And why that ye be clad thus all in black?\"\n"
"\n"
"The oldest lady of them all then spake,\n"
"When she had swooned, with a deadly cheer*,                 *countenance\n"
"That it was ruthe* for to see or hear.                             *pity\n"
"She saide; \"Lord, to whom fortune hath given\n"
"Vict'ry, and as a conqueror to liven,\n"
"Nought grieveth us your glory and your honour;\n"
"But we beseechen mercy and succour.\n"
"Have mercy on our woe and our distress;\n"
"Some drop of pity, through thy gentleness,\n"
"Upon us wretched women let now fall.\n"
"For certes, lord, there is none of us all\n"
"That hath not been a duchess or a queen;\n"
"Now be we caitives*, as it is well seen:                       *captives\n"
"Thanked be Fortune, and her false wheel,\n"
"That *none estate ensureth to be wele*.       *assures no continuance of\n"
"And certes, lord, t'abiden your presence              prosperous estate*\n"
"Here in this temple of the goddess Clemence\n"
"We have been waiting all this fortenight:\n"
"Now help us, lord, since it lies in thy might.\n"
"\n"
"\"I, wretched wight, that weep and waile thus,\n"
"Was whilom wife to king Capaneus,\n"
"That starf* at Thebes, cursed be that day:                     *died <7>\n"
"And alle we that be in this array,\n"
"And maken all this lamentatioun,\n"
"We losten all our husbands at that town,\n"
"While that the siege thereabouten lay.\n"
"And yet the olde Creon, wellaway!\n"
"That lord is now of Thebes the city,\n"
"Fulfilled of ire and of iniquity,\n"
"He for despite, and for his tyranny,\n"
"To do the deade bodies villainy*,                                *insult\n"
"Of all our lorde's, which that been y-slaw,                       *slain\n"
"Hath all the bodies on an heap y-draw,\n"
"And will not suffer them by none assent\n"
"Neither to be y-buried, nor y-brent*,                             *burnt\n"
"But maketh houndes eat them in despite.\"\n"
"And with that word, withoute more respite\n"
"They fallen groff,* and cryden piteously;                    *grovelling\n"
"\"Have on us wretched women some mercy,\n"
"And let our sorrow sinken in thine heart.\"\n"
"\n"
"This gentle Duke down from his courser start\n"
"With hearte piteous, when he heard them speak.\n"
"Him thoughte that his heart would all to-break,\n"
"When he saw them so piteous and so mate*                         *abased\n"
"That whilom weren of so great estate.\n"
"And in his armes he them all up hent*,                     *raised, took\n"
"And them comforted in full good intent,\n"
"And swore his oath, as he was true knight,\n"
"He woulde do *so farforthly his might*        *as far as his power went*\n"
"Upon the tyrant Creon them to wreak*,                            *avenge\n"
"That all the people of Greece shoulde speak,\n"
"How Creon was of Theseus y-served,\n"
"As he that had his death full well deserved.\n"
"And right anon withoute more abode*                               *delay\n"
"His banner he display'd, and forth he rode\n"
"To Thebes-ward, and all his, host beside:\n"
"No ner* Athenes would he go nor ride,                            *nearer\n"
"Nor take his ease fully half a day,\n"
"But onward on his way that night he lay:\n"
"And sent anon Hippolyta the queen,\n"
"And Emily her younge sister sheen*                       *bright, lovely\n"
"Unto the town of Athens for to dwell:\n"
"And forth he rit*; there is no more to tell.                       *rode\n"
"\n"
"The red statue of Mars with spear and targe*                     *shield\n"
"So shineth in his white banner large\n"
"That all the fieldes glitter up and down:\n"
"And by his banner borne is his pennon\n"
"Of gold full rich, in which there was y-beat*                   *stamped\n"
"The Minotaur<8> which that he slew in Crete\n"
"Thus rit this Duke, thus rit this conqueror\n"
"And in his host of chivalry the flower,\n"
"Till that he came to Thebes, and alight\n"
"Fair in a field, there as he thought to fight.\n"
"But shortly for to speaken of this thing,\n"
"With Creon, which that was of Thebes king,\n"
"He fought, and slew him manly as a knight\n"
"In plain bataille, and put his folk to flight:\n"
"And by assault he won the city after,\n"
"And rent adown both wall, and spar, and rafter;\n"
"And to the ladies he restored again\n"
"The bodies of their husbands that were slain,\n"
"To do obsequies, as was then the guise*.                         *custom\n"
"\n"
"But it were all too long for to devise*                        *describe\n"
"The greate clamour, and the waimenting*,                      *lamenting\n"
"Which that the ladies made at the brenning*                     *burning\n"
"Of the bodies, and the great honour\n"
"That Theseus the noble conqueror\n"
"Did to the ladies, when they from him went:\n"
"But shortly for to tell is mine intent.\n"
"When that this worthy Duke, this Theseus,\n"
"Had Creon slain, and wonnen Thebes thus,\n"
"Still in the field he took all night his rest,\n"
"And did with all the country as him lest*.                      *pleased\n"
"To ransack in the tas* of bodies dead,                             *heap\n"
"Them for to strip of *harness and of **weed,           *armour **clothes\n"
"The pillers* did their business and cure,                 *pillagers <9>\n"
"After the battle and discomfiture.\n"
"And so befell, that in the tas they found,\n"
"Through girt with many a grievous bloody wound,\n"
"Two younge knightes *ligging by and by*             *lying side by side*\n"
"Both in *one armes*, wrought full richely:             *the same armour*\n"
"Of whiche two, Arcita hight that one,\n"
"And he that other highte Palamon.\n"
"Not fully quick*, nor fully dead they were,                       *alive\n"
"But by their coat-armour, and by their gear,\n"
"The heralds knew them well in special,\n"
"As those that weren of the blood royal\n"
"Of Thebes, and *of sistren two y-born*.            *born of two sisters*\n"
"Out of the tas the pillers have them torn,\n"
"And have them carried soft unto the tent\n"
"Of Theseus, and he full soon them sent\n"
"To Athens, for to dwellen in prison\n"
"Perpetually, he *n'olde no ranson*.               *would take no ransom*\n"
"And when this worthy Duke had thus y-done,\n"
"He took his host, and home he rit anon\n"
"With laurel crowned as a conquerour;\n"
"And there he lived in joy and in honour\n"
"Term of his life; what needeth wordes mo'?\n"
"And in a tower, in anguish and in woe,\n"
"Dwellen this Palamon, and eke Arcite,\n"
"For evermore, there may no gold them quite*                    *set free\n"
"\n"
"Thus passed year by year, and day by day,\n"
"Till it fell ones in a morn of May\n"
"That Emily, that fairer was to seen\n"
"Than is the lily upon his stalke green,\n"
"And fresher than the May with flowers new\n"
"(For with the rose colour strove her hue;\n"
"I n'ot* which was the finer of them two),                      *know not\n"
"Ere it was day, as she was wont to do,\n"
"She was arisen, and all ready dight*,                           *dressed\n"
"For May will have no sluggardy a-night;\n"
"The season pricketh every gentle heart,\n"
"And maketh him out of his sleep to start,\n"
"And saith, \"Arise, and do thine observance.\"\n"
"\n"
"This maketh Emily have remembrance\n"
"To do honour to May, and for to rise.\n"
"Y-clothed was she fresh for to devise;\n"
"Her yellow hair was braided in a tress,\n"
"Behind her back, a yarde long I guess.\n"
"And in the garden at *the sun uprist*                           *sunrise\n"
"She walketh up and down where as her list.\n"
"She gathereth flowers, party* white and red,                    *mingled\n"
"To make a sotel* garland for her head,            *subtle, well-arranged\n"
"And as an angel heavenly she sung.\n"
"The greate tower, that was so thick and strong,\n"
"Which of the castle was the chief dungeon<10>\n"
"(Where as these knightes weren in prison,\n"
"Of which I tolde you, and telle shall),\n"
"Was even joinant* to the garden wall,                         *adjoining\n"
"There as this Emily had her playing.\n"
"\n"
"Bright was the sun, and clear that morrowning,\n"
"And Palamon, this woful prisoner,\n"
"As was his wont, by leave of his gaoler,\n"
"Was ris'n, and roamed in a chamber on high,\n"
"In which he all the noble city sigh*,                               *saw\n"
"And eke the garden, full of branches green,\n"
"There as this fresh Emelia the sheen\n"
"Was in her walk, and roamed up and down.\n"
"This sorrowful prisoner, this Palamon\n"
"Went in his chamber roaming to and fro,\n"
"And to himself complaining of his woe:\n"
"That he was born, full oft he said, Alas!\n"
"And so befell, by aventure or cas*,                              *chance\n"
"That through a window thick of many a bar\n"
"Of iron great, and square as any spar,\n"
"He cast his eyes upon Emelia,\n"
"And therewithal he blent* and cried, Ah!                  *started aside\n"
"As though he stungen were unto the heart.\n"
"And with that cry Arcite anon up start,\n"
"And saide, \"Cousin mine, what aileth thee,\n"
"That art so pale and deadly for to see?\n"
"Why cried'st thou? who hath thee done offence?\n"
"For Godde's love, take all in patience\n"
"Our prison*, for it may none other be.                     *imprisonment\n"
"Fortune hath giv'n us this adversity'.\n"
"Some wick'* aspect or disposition                                *wicked\n"
"Of Saturn<11>, by some constellation,\n"
"Hath giv'n us this, although we had it sworn,\n"
"So stood the heaven when that we were born,\n"
"We must endure; this is the short and plain.\n"
"\n"
"This Palamon answer'd, and said again:\n"
"\"Cousin, forsooth of this opinion\n"
"Thou hast a vain imagination.\n"
"This prison caused me not for to cry;\n"
"But I was hurt right now thorough mine eye\n"
"Into mine heart; that will my bane*  be.                    *destruction\n"
"The fairness of the lady that I see\n"
"Yond in the garden roaming to and fro,\n"
"Is cause of all my crying and my woe.\n"
"I *n'ot wher* she be woman or goddess,                *know not whether*\n"
"But Venus is it, soothly* as I guess,                             *truly\n"
"And therewithal on knees adown he fill,\n"
"And saide: \"Venus, if it be your will\n"
"You in this garden thus to transfigure\n"
"Before me sorrowful wretched creature,\n"
"Out of this prison help that we may scape.\n"
"And if so be our destiny be shape\n"
"By etern word to dien in prison,\n"
"Of our lineage have some compassion,\n"
"That is so low y-brought by tyranny.\"\n"
"\n"
"And with that word Arcita *gan espy*               *began to look forth*\n"
"Where as this lady roamed to and fro\n"
"And with that sight her beauty hurt him so,\n"
"That if that Palamon was wounded sore,\n"
"Arcite is hurt as much as he, or more.\n"
"And with a sigh he saide piteously:\n"
"\"The freshe beauty slay'th me suddenly\n"
"Of her that roameth yonder in the place.\n"
"And but* I have her mercy and her grace,                         *unless\n"
"That I may see her at the leaste way,\n"
"I am but dead; there is no more to say.\"\n"
"This Palamon, when he these wordes heard,\n"
"Dispiteously* he looked, and answer'd:                          *angrily\n"
"\"Whether say'st thou this in earnest or in play?\"\n"
"\"Nay,\" quoth Arcite, \"in earnest, by my fay*.                     *faith\n"
"God help me so, *me lust full ill to play*.\"          *I am in no humour\n"
"This Palamon gan knit his browes tway.                      for jesting*\n"
"\"It were,\" quoth he, \"to thee no great honour\n"
"For to be false, nor for to be traitour\n"
};

void setup() {
  int i=0;
  uint8_t c;
  Serial.begin(9600);
  do {
    c = pgm_read_byte(knightsTale+i);
    if (c) Serial.print(c,BYTE);
    i++;
  } while (c);
}
void loop() {
}
