// Text is an extract from The Canterbury Tales
// Full text at http://www.gutenberg.org/dirs/etext00/cbtls12.txt
#include <avr/pgmspace.h>

prog_char knightsTale[] PROGMEM= {
"                     THE KNIGHT'S TALE <1>\n"
"\n"
"\n"
"WHILOM*, as olde stories tellen us,                            *formerly\n"
"There was a duke that highte* Theseus.                   *was called <2>\n"
"Of Athens he was lord and governor,\n"
"And in his time such a conqueror\n"
"That greater was there none under the sun.\n"
"Full many a riche country had he won.\n"
"What with his wisdom and his chivalry,\n"
"He conquer'd all the regne of Feminie,<3>\n"
"That whilom was y-cleped Scythia;\n"
"And weddede the Queen Hippolyta\n"
"And brought her home with him to his country\n"
"With muchel* glory and great solemnity,                           *great\n"
"And eke her younge sister Emily,\n"
"And thus with vict'ry and with melody\n"
"Let I this worthy Duke to Athens ride,\n"
"And all his host, in armes him beside.\n"
"\n"
"And certes, if it n'ere* too long to hear,                     *were not\n"
"I would have told you fully the mannere,\n"
"How wonnen* was the regne of Feminie, <4>                           *won\n"
"By Theseus, and by his chivalry;\n"
"And of the greate battle for the nonce\n"
"Betwixt Athenes and the Amazons;\n"
"And how assieged was Hippolyta,\n"
"The faire hardy queen of Scythia;\n"
"And of the feast that was at her wedding\n"
"And of the tempest at her homecoming.\n"
"But all these things I must as now forbear.\n"
"I have, God wot, a large field to ear*                       *plough<5>;\n"
"And weake be the oxen in my plough;\n"
"The remnant of my tale is long enow.\n"
"I will not *letten eke none of this rout*.                *hinder any of\n"
"Let every fellow tell his tale about,                      this company*\n"
"And let see now who shall the supper win.\n"
"There *as I left*, I will again begin.                *where I left off*\n"
"\n"
"This Duke, of whom I make mentioun,\n"
"When he was come almost unto the town,\n"
"In all his weal, and in his moste pride,\n"
"He was ware, as he cast his eye aside,\n"
"Where that there kneeled in the highe way\n"
"A company of ladies, tway and tway,\n"
"Each after other, clad in clothes black:\n"
"But such a cry and such a woe they make,\n"
"That in this world n'is creature living,\n"
"That hearde such another waimenting*                      *lamenting <6>\n"
"And of this crying would they never stenten*,                    *desist\n"
"Till they the reines of his bridle henten*.                       *seize\n"
"\"What folk be ye that at mine homecoming\n"
"Perturben so my feaste with crying?\"\n"
"Quoth Theseus; \"Have ye so great envy\n"
"Of mine honour, that thus complain and cry?\n"
"Or who hath you misboden*, or offended?                         *wronged\n"
"Do telle me, if it may be amended;\n"
"And why that ye be clad thus all in black?\"\n"
"\n"
"The oldest lady of them all then spake,\n"
"When she had swooned, with a deadly cheer*,                 *countenance\n"
"That it was ruthe* for to see or hear.                             *pity\n"
"She saide; \"Lord, to whom fortune hath given\n"
"Vict'ry, and as a conqueror to liven,\n"
"Nought grieveth us your glory and your honour;\n"
"But we beseechen mercy and succour.\n"
"Have mercy on our woe and our distress;\n"
"Some drop of pity, through thy gentleness,\n"
"Upon us wretched women let now fall.\n"
"For certes, lord, there is none of us all\n"
"That hath not been a duchess or a queen;\n"
"Now be we caitives*, as it is well seen:                       *captives\n"
"Thanked be Fortune, and her false wheel,\n"
"That *none estate ensureth to be wele*.       *assures no continuance of\n"
"And certes, lord, t'abiden your presence              prosperous estate*\n"
"Here in this temple of the goddess Clemence\n"
"We have been waiting all this fortenight:\n"
"Now help us, lord, since it lies in thy might.\n"
"\n"
"\"I, wretched wight, that weep and waile thus,\n"
"Was whilom wife to king Capaneus,\n"
"That starf* at Thebes, cursed be that day:                     *died <7>\n"
"And alle we that be in this array,\n"
"And maken all this lamentatioun,\n"
"We losten all our husbands at that town,\n"
"While that the siege thereabouten lay.\n"
"And yet the olde Creon, wellaway!\n"
"That lord is now of Thebes the city,\n"
"Fulfilled of ire and of iniquity,\n"
"He for despite, and for his tyranny,\n"
"To do the deade bodies villainy*,                                *insult\n"
"Of all our lorde's, which that been y-slaw,                       *slain\n"
"Hath all the bodies on an heap y-draw,\n"
"And will not suffer them by none assent\n"
"Neither to be y-buried, nor y-brent*,                             *burnt\n"
"But maketh houndes eat them in despite.\"\n"
"And with that word, withoute more respite\n"
"They fallen groff,* and cryden piteously;                    *grovelling\n"
"\"Have on us wretched women some mercy,\n"
"And let our sorrow sinken in thine heart.\"\n"
"\n"
"This gentle Duke down from his courser start\n"
"With hearte piteous, when he heard them speak.\n"
"Him thoughte that his heart would all to-break,\n"
"When he saw them so piteous and so mate*                         *abased\n"
"That whilom weren of so great estate.\n"
"And in his armes he them all up hent*,                     *raised, took\n"
"And them comforted in full good intent,\n"
"And swore his oath, as he was true knight,\n"
"He woulde do *so farforthly his might*        *as far as his power went*\n"
"Upon the tyrant Creon them to wreak*,                            *avenge\n"
"That all the people of Greece shoulde speak,\n"
"How Creon was of Theseus y-served,\n"
"As he that had his death full well deserved.\n"
"And right anon withoute more abode*                               *delay\n"
"His banner he display'd, and forth he rode\n"
"To Thebes-ward, and all his, host beside:\n"
"No ner* Athenes would he go nor ride,                            *nearer\n"
"Nor take his ease fully half a day,\n"
"But onward on his way that night he lay:\n"
"And sent anon Hippolyta the queen,\n"
"And Emily her younge sister sheen*                       *bright, lovely\n"
"Unto the town of Athens for to dwell:\n"
"And forth he rit*; there is no more to tell.                       *rode\n"
"\n"
"The red statue of Mars with spear and targe*                     *shield\n"
"So shineth in his white banner large\n"
"That all the fieldes glitter up and down:\n"
"And by his banner borne is his pennon\n"
"Of gold full rich, in which there was y-beat*                   *stamped\n"
"The Minotaur<8> which that he slew in Crete\n"
"Thus rit this Duke, thus rit this conqueror\n"
"And in his host of chivalry the flower,\n"
"Till that he came to Thebes, and alight\n"
"Fair in a field, there as he thought to fight.\n"
"But shortly for to speaken of this thing,\n"
"With Creon, which that was of Thebes king,\n"
"He fought, and slew him manly as a knight\n"
"In plain bataille, and put his folk to flight:\n"
"And by assault he won the city after,\n"
"And rent adown both wall, and spar, and rafter;\n"
"And to the ladies he restored again\n"
"The bodies of their husbands that were slain,\n"
"To do obsequies, as was then the guise*.                         *custom\n"
"\n"
"But it were all too long for to devise*                        *describe\n"
"The greate clamour, and the waimenting*,                      *lamenting\n"
"Which that the ladies made at the brenning*                     *burning\n"
"Of the bodies, and the great honour\n"
"That Theseus the noble conqueror\n"
"Did to the ladies, when they from him went:\n"
"But shortly for to tell is mine intent.\n"
"When that this worthy Duke, this Theseus,\n"
"Had Creon slain, and wonnen Thebes thus,\n"
"Still in the field he took all night his rest,\n"
"And did with all the country as him lest*.                      *pleased\n"
"To ransack in the tas* of bodies dead,                             *heap\n"
"Them for to strip of *harness and of **weed,           *armour **clothes\n"
"The pillers* did their business and cure,                 *pillagers <9>\n"
"After the battle and discomfiture.\n"
"And so befell, that in the tas they found,\n"
"Through girt with many a grievous bloody wound,\n"
"Two younge knightes *ligging by and by*             *lying side by side*\n"
"Both in *one armes*, wrought full richely:             *the same armour*\n"
"Of whiche two, Arcita hight that one,\n"
"And he that other highte Palamon.\n"
"Not fully quick*, nor fully dead they were,                       *alive\n"
"But by their coat-armour, and by their gear,\n"
"The heralds knew them well in special,\n"
"As those that weren of the blood royal\n"
"Of Thebes, and *of sistren two y-born*.            *born of two sisters*\n"
"Out of the tas the pillers have them torn,\n"
"And have them carried soft unto the tent\n"
"Of Theseus, and he full soon them sent\n"
"To Athens, for to dwellen in prison\n"
"Perpetually, he *n'olde no ranson*.               *would take no ransom*\n"
"And when this worthy Duke had thus y-done,\n"
"He took his host, and home he rit anon\n"
"With laurel crowned as a conquerour;\n"
"And there he lived in joy and in honour\n"
"Term of his life; what needeth wordes mo'?\n"
"And in a tower, in anguish and in woe,\n"
"Dwellen this Palamon, and eke Arcite,\n"
"For evermore, there may no gold them quite*                    *set free\n"
"\n"
"Thus passed year by year, and day by day,\n"
"Till it fell ones in a morn of May\n"
"That Emily, that fairer was to seen\n"
"Than is the lily upon his stalke green,\n"
"And fresher than the May with flowers new\n"
"(For with the rose colour strove her hue;\n"
"I n'ot* which was the finer of them two),                      *know not\n"
"Ere it was day, as she was wont to do,\n"
"She was arisen, and all ready dight*,                           *dressed\n"
"For May will have no sluggardy a-night;\n"
"The season pricketh every gentle heart,\n"
"And maketh him out of his sleep to start,\n"
"And saith, \"Arise, and do thine observance.\"\n"
"\n"
"This maketh Emily have remembrance\n"
"To do honour to May, and for to rise.\n"
"Y-clothed was she fresh for to devise;\n"
"Her yellow hair was braided in a tress,\n"
"Behind her back, a yarde long I guess.\n"
"And in the garden at *the sun uprist*                           *sunrise\n"
"She walketh up and down where as her list.\n"
"She gathereth flowers, party* white and red,                    *mingled\n"
"To make a sotel* garland for her head,            *subtle, well-arranged\n"
"And as an angel heavenly she sung.\n"
"The greate tower, that was so thick and strong,\n"
"Which of the castle was the chief dungeon<10>\n"
"(Where as these knightes weren in prison,\n"
"Of which I tolde you, and telle shall),\n"
"Was even joinant* to the garden wall,                         *adjoining\n"
"There as this Emily had her playing.\n"
"\n"
"Bright was the sun, and clear that morrowning,\n"
"And Palamon, this woful prisoner,\n"
"As was his wont, by leave of his gaoler,\n"
"Was ris'n, and roamed in a chamber on high,\n"
"In which he all the noble city sigh*,                               *saw\n"
"And eke the garden, full of branches green,\n"
"There as this fresh Emelia the sheen\n"
"Was in her walk, and roamed up and down.\n"
"This sorrowful prisoner, this Palamon\n"
"Went in his chamber roaming to and fro,\n"
"And to himself complaining of his woe:\n"
"That he was born, full oft he said, Alas!\n"
"And so befell, by aventure or cas*,                              *chance\n"
"That through a window thick of many a bar\n"
"Of iron great, and square as any spar,\n"
"He cast his eyes upon Emelia,\n"
"And therewithal he blent* and cried, Ah!                  *started aside\n"
"As though he stungen were unto the heart.\n"
"And with that cry Arcite anon up start,\n"
"And saide, \"Cousin mine, what aileth thee,\n"
"That art so pale and deadly for to see?\n"
"Why cried'st thou? who hath thee done offence?\n"
"For Godde's love, take all in patience\n"
"Our prison*, for it may none other be.                     *imprisonment\n"
"Fortune hath giv'n us this adversity'.\n"
"Some wick'* aspect or disposition                                *wicked\n"
"Of Saturn<11>, by some constellation,\n"
"Hath giv'n us this, although we had it sworn,\n"
"So stood the heaven when that we were born,\n"
"We must endure; this is the short and plain.\n"
"\n"
"This Palamon answer'd, and said again:\n"
"\"Cousin, forsooth of this opinion\n"
"Thou hast a vain imagination.\n"
"This prison caused me not for to cry;\n"
"But I was hurt right now thorough mine eye\n"
"Into mine heart; that will my bane*  be.                    *destruction\n"
"The fairness of the lady that I see\n"
"Yond in the garden roaming to and fro,\n"
"Is cause of all my crying and my woe.\n"
"I *n'ot wher* she be woman or goddess,                *know not whether*\n"
"But Venus is it, soothly* as I guess,                             *truly\n"
"And therewithal on knees adown he fill,\n"
"And saide: \"Venus, if it be your will\n"
"You in this garden thus to transfigure\n"
"Before me sorrowful wretched creature,\n"
"Out of this prison help that we may scape.\n"
"And if so be our destiny be shape\n"
"By etern word to dien in prison,\n"
"Of our lineage have some compassion,\n"
"That is so low y-brought by tyranny.\"\n"
"\n"
"And with that word Arcita *gan espy*               *began to look forth*\n"
"Where as this lady roamed to and fro\n"
"And with that sight her beauty hurt him so,\n"
"That if that Palamon was wounded sore,\n"
"Arcite is hurt as much as he, or more.\n"
"And with a sigh he saide piteously:\n"
"\"The freshe beauty slay'th me suddenly\n"
"Of her that roameth yonder in the place.\n"
"And but* I have her mercy and her grace,                         *unless\n"
"That I may see her at the leaste way,\n"
"I am but dead; there is no more to say.\"\n"
"This Palamon, when he these wordes heard,\n"
"Dispiteously* he looked, and answer'd:                          *angrily\n"
"\"Whether say'st thou this in earnest or in play?\"\n"
"\"Nay,\" quoth Arcite, \"in earnest, by my fay*.                     *faith\n"
"God help me so, *me lust full ill to play*.\"          *I am in no humour\n"
"This Palamon gan knit his browes tway.                      for jesting*\n"
"\"It were,\" quoth he, \"to thee no great honour\n"
"For to be false, nor for to be traitour\n"
"To me, that am thy cousin and thy brother\n"
"Y-sworn full deep, and each of us to other,\n"
"That never for to dien in the pain <12>,\n"
"Till that the death departen shall us twain,\n"
"Neither of us in love to hinder other,\n"
"Nor in none other case, my leve* brother;                          *dear\n"
"But that thou shouldest truly farther me\n"
"In every case, as I should farther thee.\n"
"This was thine oath, and mine also certain;\n"
"I wot it well, thou dar'st it not withsayn*,                       *deny\n"
"Thus art thou of my counsel out of doubt,\n"
"And now thou wouldest falsely be about\n"
"To love my lady, whom I love and serve,\n"
"And ever shall, until mine hearte sterve*                           *die\n"
"Now certes, false Arcite, thou shalt not so\n"
"I lov'd her first, and tolde thee my woe\n"
"As to my counsel, and my brother sworn\n"
"To farther me, as I have told beforn.\n"
"For which thou art y-bounden as a knight\n"
"To helpe me, if it lie in thy might,\n"
"Or elles art thou false, I dare well sayn,\"\n"
"\n"
"This Arcita full proudly spake again:\n"
"\"Thou shalt,\" quoth he, \"be rather* false than I,                *sooner\n"
"And thou art false, I tell thee utterly;\n"
"For par amour I lov'd her first ere thou.\n"
"What wilt thou say? *thou wist it not right now*          *even now thou\n"
"Whether she be a woman or goddess.                          knowest not*\n"
"Thine is affection of holiness,\n"
"And mine is love, as to a creature:\n"
"For which I tolde thee mine aventure\n"
"As to my cousin, and my brother sworn\n"
"I pose*, that thou loved'st her beforn:                         *suppose\n"
"Wost* thou not well the olde clerke's saw<13>,                  *know'st\n"
"That who shall give a lover any law?\n"
"Love is a greater lawe, by my pan,\n"
"Than may be giv'n to any earthly man:\n"
"Therefore positive law, and such decree,\n"
"Is broke alway for love in each degree\n"
"A man must needes love, maugre his head.\n"
"He may not flee it, though he should be dead,\n"
"*All be she* maid, or widow, or else wife.              *whether she be*\n"
"And eke it is not likely all thy life\n"
"To standen in her grace, no more than I\n"
"For well thou wost thyselfe verily,\n"
"That thou and I be damned to prison\n"
"Perpetual, us gaineth no ranson.\n"
"We strive, as did the houndes for the bone;\n"
"They fought all day, and yet their part was none.\n"
"There came a kite, while that they were so wroth,\n"
"And bare away the bone betwixt them both.\n"
"And therefore at the kinge's court, my brother,\n"
"Each man for himselfe, there is no  other.\n"
"Love if thee list; for I love and aye shall\n"
"And soothly, leve brother, this is all.\n"
"Here in this prison musten we endure,\n"
"And each of us take his Aventure.\"\n"
"\n"
"Great was the strife and long between these tway,\n"
"If that I hadde leisure for to say;\n"
"But to the effect: it happen'd on a day\n"
"(To tell it you as shortly as I may),\n"
"A worthy duke that hight Perithous<14>\n"
"That fellow was to the Duke Theseus\n"
"Since thilke* day that they were children lite**          *that **little\n"
"Was come to Athens, his fellow to visite,\n"
"And for to play, as he was wont to do;\n"
"For in this world he loved no man so;\n"
"And he lov'd him as tenderly again.\n"
"So well they lov'd, as olde bookes sayn,\n"
"That when that one was dead, soothly to sayn,\n"
"His fellow went and sought him down in hell:\n"
"But of that story list me not to write.\n"
"Duke Perithous loved well Arcite,\n"
"And had him known at Thebes year by year:\n"
"And finally at request and prayere\n"
"Of Perithous, withoute ranson\n"
"Duke Theseus him let out of prison,\n"
"Freely to go, where him list over all,\n"
"In such a guise, as I you tellen shall\n"
"This was the forword*, plainly to indite,                       *promise\n"
"Betwixte Theseus and him Arcite:\n"
"That if so were, that Arcite were y-found\n"
"Ever in his life, by day or night, one stound*               *moment<15>\n"
"In any country of this Theseus,\n"
"And he were caught, it was accorded thus,\n"
"That with a sword he shoulde lose his head;\n"
"There was none other remedy nor rede*.                          *counsel\n"
"But took his leave, and homeward he him sped;\n"
"Let him beware, his necke lieth *to wed*.                    *in pledge*\n"
"\n"
"How great a sorrow suff'reth now Arcite!\n"
"The death he feeleth through his hearte smite;\n"
"He weepeth, waileth, crieth piteously;\n"
"To slay himself he waiteth privily.\n"
"He said; \"Alas the day that I was born!\n"
"Now is my prison worse than beforn:\n"
"*Now is me shape* eternally to dwell                *it is fixed for me*\n"
"Not in purgatory, but right in hell.\n"
"Alas! that ever I knew Perithous.\n"
"For elles had I dwelt with Theseus\n"
"Y-fettered in his prison evermo'.\n"
"Then had I been in bliss, and not in woe.\n"
"Only the sight of her, whom that I serve,\n"
"Though that I never may her grace deserve,\n"
"Would have sufficed right enough for me.\n"
"O deare cousin Palamon,\" quoth he,\n"
"\"Thine is the vict'ry of this aventure,\n"
"Full blissfully in prison to endure:\n"
"In prison? nay certes, in paradise.\n"
"Well hath fortune y-turned thee the dice,\n"
"That hast the sight of her, and I th' absence.\n"
"For possible is, since thou hast her presence,\n"
"And art a knight, a worthy and an able,\n"
"That by some cas*, since fortune is changeable,                  *chance\n"
"Thou may'st to thy desire sometime attain.\n"
"But I that am exiled, and barren\n"
"Of alle grace, and in so great despair,\n"
"That there n'is earthe, water, fire, nor air,\n"
"Nor creature, that of them maked is,\n"
"That may me helpe nor comfort in this,\n"
"Well ought I *sterve in wanhope* and distress.          *die in despair*\n"
"Farewell my life, my lust*, and my gladness.                   *pleasure\n"
"Alas, *why plainen men so in commune       *why do men so often complain\n"
"Of purveyance of God*, or of Fortune,              of God's providence?*\n"
"That giveth them full oft in many a guise\n"
"Well better than they can themselves devise?\n"
"Some man desireth for to have richess,\n"
"That cause is of his murder or great sickness.\n"
"And some man would out of his prison fain,\n"
"That in his house is of his meinie* slain.                *servants <16>\n"
"Infinite harmes be in this mattere.\n"
"We wot never what thing we pray for here.\n"
"We fare as he that drunk is as a mouse.\n"
"A drunken man wot well he hath an house,\n"
"But he wot not which is the right way thither,\n"
"And to a drunken man the way is slither*.                      *slippery\n"
"And certes in this world so fare we.\n"
"We seeke fast after felicity,\n"
"But we go wrong full often truely.\n"
"Thus we may sayen all, and namely* I,                        *especially\n"
"That ween'd*, and had a great opinion,                          *thought\n"
"That if I might escape from prison\n"
"Then had I been in joy and perfect heal,\n"
"Where now I am exiled from my weal.\n"
"Since that I may not see you, Emily,\n"
"I am but dead; there is no remedy.\"\n"
"\n"
"Upon that other side, Palamon,\n"
"When that he wist Arcita was agone,\n"
"Much sorrow maketh, that the greate tower\n"
"Resounded of his yelling and clamour\n"
"The pure* fetters on his shinnes great                        *very <17>\n"
"Were of his bitter salte teares wet.\n"
"\n"
"\"Alas!\" quoth he, \"Arcita, cousin mine,\n"
"Of all our strife, God wot, the fruit is thine.\n"
"Thou walkest now in Thebes at thy large,\n"
"And of my woe thou *givest little charge*.          *takest little heed*\n"
"Thou mayst, since thou hast wisdom and manhead*,       *manhood, courage\n"
"Assemble all the folk of our kindred,\n"
"And make a war so sharp on this country\n"
"That by some aventure, or some treaty,\n"
"Thou mayst have her to lady and to wife,\n"
"For whom that I must needes lose my life.\n"
"For as by way of possibility,\n"
"Since thou art at thy large, of prison free,\n"
"And art a lord, great is thine avantage,\n"
"More than is mine, that sterve here in a cage.\n"
"For I must weep and wail, while that I live,\n"
"With all the woe that prison may me give,\n"
"And eke with pain that love me gives also,\n"
"That doubles all my torment and my woe.\"\n"
"\n"
"Therewith the fire of jealousy upstart\n"
"Within his breast, and hent* him by the heart                    *seized\n"
"So woodly*, that he like was to behold                            *madly\n"
"The box-tree, or the ashes dead and cold.\n"
"Then said; \"O cruel goddess, that govern\n"
"This world with binding of your word etern*                     *eternal\n"
"And writen in the table of adamant\n"
"Your parlement* and your eternal grant,                    *consultation\n"
"What is mankind more *unto you y-hold*                  *by you esteemed\n"
"Than is the sheep, that rouketh* in the fold!      *lie huddled together\n"
"For slain is man, right as another beast;\n"
"And dwelleth eke in prison and arrest,\n"
"And hath sickness, and great adversity,\n"
"And oftentimes guilteless, pardie*                               *by God\n"
"What governance is in your prescience,\n"
"That guilteless tormenteth innocence?\n"
"And yet increaseth this all my penance,\n"
"That man is bounden to his observance\n"
"For Godde's  sake to *letten of his will*,         *restrain his desire*\n"
"Whereas a beast may all his lust fulfil.\n"
"And when a beast is dead, he hath no pain;\n"
"But man after his death must weep and plain,\n"
"Though in this worlde he have care and woe:\n"
"Withoute doubt it maye standen so.\n"
"\"The answer of this leave I to divines,\n"
"But well I wot, that in this world great pine* is;        *pain, trouble\n"
"Alas! I see a serpent or a thief\n"
"That many a true man hath done mischief,\n"
"Go at his large, and where him list may turn.\n"
"But I must be in prison through Saturn,\n"
"And eke through Juno, jealous and eke wood*,                        *mad\n"
"That hath well nigh destroyed all the blood\n"
"Of Thebes, with his waste walles wide.\n"
"And Venus slay'th me on that other side\n"
"For jealousy, and fear of him, Arcite.\"\n"
"\n"
"Now will I stent* of Palamon a lite**,                   *pause **little\n"
"And let him in his prison stille dwell,\n"
"And of Arcita forth I will you tell.\n"
"The summer passeth, and the nightes long\n"
"Increase double-wise the paines strong\n"
"Both of the lover and the prisonere.\n"
"I n'ot* which hath the wofuller mistere**.         *know not **condition\n"
"For, shortly for to say, this Palamon\n"
"Perpetually is damned to prison,\n"
"In chaines and in fetters to be dead;\n"
"And Arcite is exiled *on his head*                *on peril of his head*\n"
"For evermore as out of that country,\n"
"Nor never more he shall his lady see.\n"
"You lovers ask I now this question,<18>\n"
"Who lieth the worse, Arcite or Palamon?\n"
"The one may see his lady day by day,\n"
"But in prison he dwelle must alway.\n"
"The other where him list may ride or go,\n"
"But see his lady shall he never mo'.\n"
"Now deem all as you liste, ye that can,\n"
"For I will tell you forth as I began.\n"
"\n"
"When that Arcite to Thebes comen was,\n"
"Full oft a day he swelt*, and said, \"Alas!\"                     *fainted\n"
"For see this lady he shall never mo'.\n"
"And shortly to concluden all his woe,\n"
"So much sorrow had never creature\n"
"That is or shall be while the world may dure.\n"
"His sleep, his meat, his drink is *him byraft*,    *taken away from him*\n"
"That lean he wex*, and dry as any shaft.                         *became\n"
"His eyen hollow, grisly to behold,\n"
"His hue sallow, and pale as ashes cold,\n"
"And solitary he was, ever alone,\n"
"And wailing all the night, making his moan.\n"
"And if he hearde song or instrument,\n"
"Then would he weepen, he might not be stent*.                   *stopped\n"
"So feeble were his spirits, and so low,\n"
"And changed so, that no man coulde know\n"
"His speech, neither his voice, though men it heard.\n"
"And in his gear* for all the world he far'd              *behaviour <19>\n"
"Not only like the lovers' malady\n"
"Of Eros, but rather y-like manie*                               *madness\n"
"Engender'd of humours melancholic,\n"
"Before his head in his cell fantastic.<20>\n"
"And shortly turned was all upside down,\n"
"Both habit and eke dispositioun,\n"
"Of him, this woful lover Dan* Arcite.                         *Lord <21>\n"
"Why should I all day of his woe indite?\n"
"When he endured had a year or two\n"
"This cruel torment, and this pain and woe,\n"
"At Thebes, in his country, as I said,\n"
"Upon a night in sleep as he him laid,\n"
"Him thought how that the winged god Mercury\n"
"Before him stood, and bade him to be merry.\n"
"His sleepy yard* in hand he bare upright;                      *rod <22>\n"
"A hat he wore upon his haires bright.\n"
"Arrayed was this god (as he took keep*)                          *notice\n"
"As he was when that Argus<23> took his sleep;\n"
"And said him thus: \"To Athens shalt thou wend*;                      *go\n"
"There is thee shapen* of thy woe an end.\"               *fixed, prepared\n"
"And with that word Arcite woke and start.\n"
"\"Now truely how sore that e'er me smart,\"\n"
"Quoth he, \"to Athens right now will I fare.\n"
"Nor for no dread of death shall I not spare\n"
"To see my lady that I love and serve;\n"
"In her presence *I recke not to sterve.*\"         *do not care if I die*\n"
"And with that word he caught a great mirror,\n"
"And saw that changed was all his colour,\n"
"And saw his visage all in other kind.\n"
"And right anon it ran him ill his mind,\n"
"That since his face was so disfigur'd\n"
"Of malady the which he had endur'd,\n"
"He mighte well, if that he *bare him low,*      *lived in lowly fashion*\n"
"Live in Athenes evermore unknow,\n"
"And see his lady wellnigh day by day.\n"
"And right anon he changed his array,\n"
"And clad him as a poore labourer.\n"
"And all alone, save only a squier,\n"
"That knew his privity* and all his cas**,             *secrets **fortune\n"
"Which was disguised poorly as he was,\n"
"To Athens is he gone the nexte*  way.                      *nearest <24>\n"
"And to the court he went upon a day,\n"
"And at the gate he proffer'd his service,\n"
"To drudge and draw, what so men would devise*.                    *order\n"
"And, shortly of this matter for to sayn,\n"
"He fell in office with a chamberlain,\n"
"The which that dwelling was with Emily.\n"
"For he was wise, and coulde soon espy\n"
"Of every servant which that served her.\n"
"Well could he hewe wood, and water bear,\n"
"For he was young and mighty for the nones*,                    *occasion\n"
"And thereto he was strong and big of bones\n"
"To do that any wight can him devise.\n"
"\n"
"A year or two he was in this service,\n"
"Page of the chamber of Emily the bright;\n"
"And Philostrate he saide that he hight.\n"
"But half so well belov'd a man as he\n"
"Ne was there never in court of his degree.\n"
"He was so gentle of conditioun,\n"
"That throughout all the court was his renown.\n"
"They saide that it were a charity\n"
"That Theseus would *enhance his degree*,           *elevate him in rank*\n"
"And put him in some worshipful service,\n"
"There as he might his virtue exercise.\n"
"And thus within a while his name sprung\n"
"Both of his deedes, and of his good tongue,\n"
"That Theseus hath taken him so near,\n"
"That of his chamber he hath made him squire,\n"
"And gave him gold to maintain his degree;\n"
"And eke men brought him out of his country\n"
"From year to year full privily his rent.\n"
"But honestly and slyly* he it spent,              *discreetly, prudently\n"
"That no man wonder'd how that he it had.\n"
"And three year in this wise his life be lad*,                       *led\n"
"And bare him so in peace and eke in werre*,                         *war\n"
"There was no man that Theseus had so derre*.                       *dear\n"
"And in this blisse leave I now Arcite,\n"
"And speak I will of Palamon a lite*.                             *little\n"
"\n"
"In darkness horrible, and strong prison,\n"
"This seven year hath sitten Palamon,\n"
"Forpined*, what for love, and for distress.          *pined, wasted away\n"
"Who feeleth double sorrow and heaviness\n"
"But Palamon? that love distraineth* so,                        *afflicts\n"
"That wood* out of his wits he went for woe,                         *mad\n"
"And eke thereto he is a prisonere\n"
"Perpetual, not only for a year.\n"
"Who coulde rhyme in English properly\n"
"His martyrdom? forsooth*, it is not I;                            *truly\n"
"Therefore I pass as lightly as I may.\n"
"It fell that in the seventh year, in May\n"
"The thirde night (as olde bookes sayn,\n"
"That all this story tellen more plain),\n"
"Were it by a venture or destiny\n"
"(As when a thing is shapen* it shall be),              *settled, decreed\n"
"That soon after the midnight, Palamon\n"
"By helping of a friend brake his prison,\n"
"And fled the city fast as he might go,\n"
"For he had given drink his gaoler so\n"
"Of a clary <25>, made of a certain wine,\n"
"With *narcotise and opie* of Thebes fine,          *narcotics and opium*\n"
"That all the night, though that men would him shake,\n"
"The gaoler slept, he mighte not awake:\n"
"And thus he fled as fast as ever he may.\n"
"The night was short, and *faste by the day            *close at hand was\n"
"That needes cast he must himself to hide*.          the day during which\n"
"And to a grove faste there beside       he must cast about, or contrive,\n"
"With dreadful foot then stalked Palamon.            to conceal himself.*\n"
"For shortly this was his opinion,\n"
"That in the grove he would him hide all day,\n"
"And in the night then would he take his way\n"
"To Thebes-ward, his friendes for to pray\n"
"On Theseus to help him to warray*.                        *make war <26>\n"
"And shortly either he would lose his life,\n"
"Or winnen Emily unto his wife.\n"
"This is th' effect, and his intention plain.\n"
"\n"
"Now will I turn to Arcita again,\n"
"That little wist how nighe was his care,\n"
"Till that Fortune had brought him in the snare.\n"
"The busy lark, the messenger of day,\n"
"Saluteth in her song the morning gray;\n"
};

void setup() {
  int i=0;
  uint8_t c;
  Serial.begin(9600);
  do {
    c = pgm_read_byte(knightsTale+i);
    if (c) Serial.print(c,BYTE);
    i++;
  } while (c);
}
void loop() {
}
