// Text is an extract from The Canterbury Tales
// Full text at http://www.gutenberg.org/dirs/etext00/cbtls12.txt
#include <avr/pgmspace.h>

prog_char knightsTale[] PROGMEM= {
"                     THE KNIGHT'S TALE <1>\n"
"\n"
"\n"
"WHILOM*, as olde stories tellen us,                            *formerly\n"
"There was a duke that highte* Theseus.                   *was called <2>\n"
"Of Athens he was lord and governor,\n"
"And in his time such a conqueror\n"
"That greater was there none under the sun.\n"
"Full many a riche country had he won.\n"
"What with his wisdom and his chivalry,\n"
"He conquer'd all the regne of Feminie,<3>\n"
"That whilom was y-cleped Scythia;\n"
"And weddede the Queen Hippolyta\n"
"And brought her home with him to his country\n"
"With muchel* glory and great solemnity,                           *great\n"
"And eke her younge sister Emily,\n"
"And thus with vict'ry and with melody\n"
"Let I this worthy Duke to Athens ride,\n"
"And all his host, in armes him beside.\n"
"\n"
"And certes, if it n'ere* too long to hear,                     *were not\n"
"I would have told you fully the mannere,\n"
"How wonnen* was the regne of Feminie, <4>                           *won\n"
"By Theseus, and by his chivalry;\n"
"And of the greate battle for the nonce\n"
"Betwixt Athenes and the Amazons;\n"
"And how assieged was Hippolyta,\n"
"The faire hardy queen of Scythia;\n"
"And of the feast that was at her wedding\n"
"And of the tempest at her homecoming.\n"
"But all these things I must as now forbear.\n"
"I have, God wot, a large field to ear*                       *plough<5>;\n"
"And weake be the oxen in my plough;\n"
"The remnant of my tale is long enow.\n"
"I will not *letten eke none of this rout*.                *hinder any of\n"
"Let every fellow tell his tale about,                      this company*\n"
"And let see now who shall the supper win.\n"
"There *as I left*, I will again begin.                *where I left off*\n"
"\n"
"This Duke, of whom I make mentioun,\n"
"When he was come almost unto the town,\n"
"In all his weal, and in his moste pride,\n"
"He was ware, as he cast his eye aside,\n"
"Where that there kneeled in the highe way\n"
"A company of ladies, tway and tway,\n"
"Each after other, clad in clothes black:\n"
"But such a cry and such a woe they make,\n"
"That in this world n'is creature living,\n"
"That hearde such another waimenting*                      *lamenting <6>\n"
"And of this crying would they never stenten*,                    *desist\n"
"Till they the reines of his bridle henten*.                       *seize\n"
"\"What folk be ye that at mine homecoming\n"
"Perturben so my feaste with crying?\"\n"
"Quoth Theseus; \"Have ye so great envy\n"
"Of mine honour, that thus complain and cry?\n"
"Or who hath you misboden*, or offended?                         *wronged\n"
"Do telle me, if it may be amended;\n"
"And why that ye be clad thus all in black?\"\n"
"\n"
"The oldest lady of them all then spake,\n"
"When she had swooned, with a deadly cheer*,                 *countenance\n"
"That it was ruthe* for to see or hear.                             *pity\n"
"She saide; \"Lord, to whom fortune hath given\n"
"Vict'ry, and as a conqueror to liven,\n"
"Nought grieveth us your glory and your honour;\n"
"But we beseechen mercy and succour.\n"
"Have mercy on our woe and our distress;\n"
"Some drop of pity, through thy gentleness,\n"
"Upon us wretched women let now fall.\n"
"For certes, lord, there is none of us all\n"
"That hath not been a duchess or a queen;\n"
"Now be we caitives*, as it is well seen:                       *captives\n"
"Thanked be Fortune, and her false wheel,\n"
"That *none estate ensureth to be wele*.       *assures no continuance of\n"
"And certes, lord, t'abiden your presence              prosperous estate*\n"
"Here in this temple of the goddess Clemence\n"
"We have been waiting all this fortenight:\n"
"Now help us, lord, since it lies in thy might.\n"
"\n"
"\"I, wretched wight, that weep and waile thus,\n"
"Was whilom wife to king Capaneus,\n"
"That starf* at Thebes, cursed be that day:                     *died <7>\n"
"And alle we that be in this array,\n"
"And maken all this lamentatioun,\n"
"We losten all our husbands at that town,\n"
"While that the siege thereabouten lay.\n"
"And yet the olde Creon, wellaway!\n"
"That lord is now of Thebes the city,\n"
"Fulfilled of ire and of iniquity,\n"
"He for despite, and for his tyranny,\n"
"To do the deade bodies villainy*,                                *insult\n"
"Of all our lorde's, which that been y-slaw,                       *slain\n"
"Hath all the bodies on an heap y-draw,\n"
"And will not suffer them by none assent\n"
"Neither to be y-buried, nor y-brent*,                             *burnt\n"
"But maketh houndes eat them in despite.\"\n"
"And with that word, withoute more respite\n"
"They fallen groff,* and cryden piteously;                    *grovelling\n"
"\"Have on us wretched women some mercy,\n"
"And let our sorrow sinken in thine heart.\"\n"
"\n"
"This gentle Duke down from his courser start\n"
"With hearte piteous, when he heard them speak.\n"
"Him thoughte that his heart would all to-break,\n"
"When he saw them so piteous and so mate*                         *abased\n"
"That whilom weren of so great estate.\n"
"And in his armes he them all up hent*,                     *raised, took\n"
"And them comforted in full good intent,\n"
"And swore his oath, as he was true knight,\n"
"He woulde do *so farforthly his might*        *as far as his power went*\n"
"Upon the tyrant Creon them to wreak*,                            *avenge\n"
"That all the people of Greece shoulde speak,\n"
"How Creon was of Theseus y-served,\n"
"As he that had his death full well deserved.\n"
"And right anon withoute more abode*                               *delay\n"
"His banner he display'd, and forth he rode\n"
"To Thebes-ward, and all his, host beside:\n"
"No ner* Athenes would he go nor ride,                            *nearer\n"
"Nor take his ease fully half a day,\n"
"But onward on his way that night he lay:\n"
"And sent anon Hippolyta the queen,\n"
"And Emily her younge sister sheen*                       *bright, lovely\n"
"Unto the town of Athens for to dwell:\n"
"And forth he rit*; there is no more to tell.                       *rode\n"
"\n"
"The red statue of Mars with spear and targe*                     *shield\n"
"So shineth in his white banner large\n"
"That all the fieldes glitter up and down:\n"
"And by his banner borne is his pennon\n"
"Of gold full rich, in which there was y-beat*                   *stamped\n"
"The Minotaur<8> which that he slew in Crete\n"
"Thus rit this Duke, thus rit this conqueror\n"
"And in his host of chivalry the flower,\n"
"Till that he came to Thebes, and alight\n"
"Fair in a field, there as he thought to fight.\n"
"But shortly for to speaken of this thing,\n"
"With Creon, which that was of Thebes king,\n"
"He fought, and slew him manly as a knight\n"
"In plain bataille, and put his folk to flight:\n"
"And by assault he won the city after,\n"
"And rent adown both wall, and spar, and rafter;\n"
"And to the ladies he restored again\n"
"The bodies of their husbands that were slain,\n"
"To do obsequies, as was then the guise*.                         *custom\n"
"\n"
"But it were all too long for to devise*                        *describe\n"
"The greate clamour, and the waimenting*,                      *lamenting\n"
"Which that the ladies made at the brenning*                     *burning\n"
"Of the bodies, and the great honour\n"
"That Theseus the noble conqueror\n"
"Did to the ladies, when they from him went:\n"
"But shortly for to tell is mine intent.\n"
"When that this worthy Duke, this Theseus,\n"
"Had Creon slain, and wonnen Thebes thus,\n"
"Still in the field he took all night his rest,\n"
"And did with all the country as him lest*.                      *pleased\n"
"To ransack in the tas* of bodies dead,                             *heap\n"
"Them for to strip of *harness and of **weed,           *armour **clothes\n"
"The pillers* did their business and cure,                 *pillagers <9>\n"
"After the battle and discomfiture.\n"
"And so befell, that in the tas they found,\n"
"Through girt with many a grievous bloody wound,\n"
"Two younge knightes *ligging by and by*             *lying side by side*\n"
"Both in *one armes*, wrought full richely:             *the same armour*\n"
"Of whiche two, Arcita hight that one,\n"
"And he that other highte Palamon.\n"
"Not fully quick*, nor fully dead they were,                       *alive\n"
"But by their coat-armour, and by their gear,\n"
"The heralds knew them well in special,\n"
"As those that weren of the blood royal\n"
"Of Thebes, and *of sistren two y-born*.            *born of two sisters*\n"
"Out of the tas the pillers have them torn,\n"
"And have them carried soft unto the tent\n"
"Of Theseus, and he full soon them sent\n"
"To Athens, for to dwellen in prison\n"
"Perpetually, he *n'olde no ranson*.               *would take no ransom*\n"
"And when this worthy Duke had thus y-done,\n"
"He took his host, and home he rit anon\n"
"With laurel crowned as a conquerour;\n"
"And there he lived in joy and in honour\n"
"Term of his life; what needeth wordes mo'?\n"
"And in a tower, in anguish and in woe,\n"
"Dwellen this Palamon, and eke Arcite,\n"
"For evermore, there may no gold them quite*                    *set free\n"
"\n"
"Thus passed year by year, and day by day,\n"
"Till it fell ones in a morn of May\n"
"That Emily, that fairer was to seen\n"
"Than is the lily upon his stalke green,\n"
"And fresher than the May with flowers new\n"
"(For with the rose colour strove her hue;\n"
"I n'ot* which was the finer of them two),                      *know not\n"
"Ere it was day, as she was wont to do,\n"
"She was arisen, and all ready dight*,                           *dressed\n"
"For May will have no sluggardy a-night;\n"
"The season pricketh every gentle heart,\n"
"And maketh him out of his sleep to start,\n"
"And saith, \"Arise, and do thine observance.\"\n"
"\n"
"This maketh Emily have remembrance\n"
"To do honour to May, and for to rise.\n"
"Y-clothed was she fresh for to devise;\n"
"Her yellow hair was braided in a tress,\n"
"Behind her back, a yarde long I guess.\n"
"And in the garden at *the sun uprist*                           *sunrise\n"
"She walketh up and down where as her list.\n"
"She gathereth flowers, party* white and red,                    *mingled\n"
"To make a sotel* garland for her head,            *subtle, well-arranged\n"
"And as an angel heavenly she sung.\n"
"The greate tower, that was so thick and strong,\n"
"Which of the castle was the chief dungeon<10>\n"
"(Where as these knightes weren in prison,\n"
"Of which I tolde you, and telle shall),\n"
"Was even joinant* to the garden wall,                         *adjoining\n"
"There as this Emily had her playing.\n"
"\n"
"Bright was the sun, and clear that morrowning,\n"
"And Palamon, this woful prisoner,\n"
"As was his wont, by leave of his gaoler,\n"
"Was ris'n, and roamed in a chamber on high,\n"
"In which he all the noble city sigh*,                               *saw\n"
"And eke the garden, full of branches green,\n"
"There as this fresh Emelia the sheen\n"
"Was in her walk, and roamed up and down.\n"
"This sorrowful prisoner, this Palamon\n"
"Went in his chamber roaming to and fro,\n"
"And to himself complaining of his woe:\n"
"That he was born, full oft he said, Alas!\n"
"And so befell, by aventure or cas*,                              *chance\n"
"That through a window thick of many a bar\n"
"Of iron great, and square as any spar,\n"
"He cast his eyes upon Emelia,\n"
"And therewithal he blent* and cried, Ah!                  *started aside\n"
"As though he stungen were unto the heart.\n"
"And with that cry Arcite anon up start,\n"
"And saide, \"Cousin mine, what aileth thee,\n"
"That art so pale and deadly for to see?\n"
"Why cried'st thou? who hath thee done offence?\n"
"For Godde's love, take all in patience\n"
"Our prison*, for it may none other be.                     *imprisonment\n"
"Fortune hath giv'n us this adversity'.\n"
"Some wick'* aspect or disposition                                *wicked\n"
"Of Saturn<11>, by some constellation,\n"
"Hath giv'n us this, although we had it sworn,\n"
"So stood the heaven when that we were born,\n"
"We must endure; this is the short and plain.\n"
"\n"
"This Palamon answer'd, and said again:\n"
"\"Cousin, forsooth of this opinion\n"
"Thou hast a vain imagination.\n"
"This prison caused me not for to cry;\n"
"But I was hurt right now thorough mine eye\n"
"Into mine heart; that will my bane*  be.                    *destruction\n"
"The fairness of the lady that I see\n"
"Yond in the garden roaming to and fro,\n"
"Is cause of all my crying and my woe.\n"
"I *n'ot wher* she be woman or goddess,                *know not whether*\n"
"But Venus is it, soothly* as I guess,                             *truly\n"
"And therewithal on knees adown he fill,\n"
"And saide: \"Venus, if it be your will\n"
"You in this garden thus to transfigure\n"
"Before me sorrowful wretched creature,\n"
"Out of this prison help that we may scape.\n"
"And if so be our destiny be shape\n"
"By etern word to dien in prison,\n"
"Of our lineage have some compassion,\n"
"That is so low y-brought by tyranny.\"\n"
"\n"
"And with that word Arcita *gan espy*               *began to look forth*\n"
"Where as this lady roamed to and fro\n"
"And with that sight her beauty hurt him so,\n"
"That if that Palamon was wounded sore,\n"
"Arcite is hurt as much as he, or more.\n"
"And with a sigh he saide piteously:\n"
"\"The freshe beauty slay'th me suddenly\n"
"Of her that roameth yonder in the place.\n"
"And but* I have her mercy and her grace,                         *unless\n"
"That I may see her at the leaste way,\n"
"I am but dead; there is no more to say.\"\n"
"This Palamon, when he these wordes heard,\n"
"Dispiteously* he looked, and answer'd:                          *angrily\n"
"\"Whether say'st thou this in earnest or in play?\"\n"
"\"Nay,\" quoth Arcite, \"in earnest, by my fay*.                     *faith\n"
"God help me so, *me lust full ill to play*.\"          *I am in no humour\n"
"This Palamon gan knit his browes tway.                      for jesting*\n"
"\"It were,\" quoth he, \"to thee no great honour\n"
"For to be false, nor for to be traitour\n"
"To me, that am thy cousin and thy brother\n"
"Y-sworn full deep, and each of us to other,\n"
"That never for to dien in the pain <12>,\n"
"Till that the death departen shall us twain,\n"
"Neither of us in love to hinder other,\n"
"Nor in none other case, my leve* brother;                          *dear\n"
"But that thou shouldest truly farther me\n"
"In every case, as I should farther thee.\n"
"This was thine oath, and mine also certain;\n"
"I wot it well, thou dar'st it not withsayn*,                       *deny\n"
"Thus art thou of my counsel out of doubt,\n"
"And now thou wouldest falsely be about\n"
"To love my lady, whom I love and serve,\n"
"And ever shall, until mine hearte sterve*                           *die\n"
"Now certes, false Arcite, thou shalt not so\n"
"I lov'd her first, and tolde thee my woe\n"
"As to my counsel, and my brother sworn\n"
"To farther me, as I have told beforn.\n"
"For which thou art y-bounden as a knight\n"
"To helpe me, if it lie in thy might,\n"
"Or elles art thou false, I dare well sayn,\"\n"
"\n"
"This Arcita full proudly spake again:\n"
"\"Thou shalt,\" quoth he, \"be rather* false than I,                *sooner\n"
"And thou art false, I tell thee utterly;\n"
"For par amour I lov'd her first ere thou.\n"
"What wilt thou say? *thou wist it not right now*          *even now thou\n"
"Whether she be a woman or goddess.                          knowest not*\n"
"Thine is affection of holiness,\n"
"And mine is love, as to a creature:\n"
"For which I tolde thee mine aventure\n"
"As to my cousin, and my brother sworn\n"
"I pose*, that thou loved'st her beforn:                         *suppose\n"
"Wost* thou not well the olde clerke's saw<13>,                  *know'st\n"
"That who shall give a lover any law?\n"
"Love is a greater lawe, by my pan,\n"
"Than may be giv'n to any earthly man:\n"
"Therefore positive law, and such decree,\n"
"Is broke alway for love in each degree\n"
"A man must needes love, maugre his head.\n"
"He may not flee it, though he should be dead,\n"
"*All be she* maid, or widow, or else wife.              *whether she be*\n"
"And eke it is not likely all thy life\n"
"To standen in her grace, no more than I\n"
"For well thou wost thyselfe verily,\n"
"That thou and I be damned to prison\n"
"Perpetual, us gaineth no ranson.\n"
"We strive, as did the houndes for the bone;\n"
"They fought all day, and yet their part was none.\n"
"There came a kite, while that they were so wroth,\n"
"And bare away the bone betwixt them both.\n"
"And therefore at the kinge's court, my brother,\n"
"Each man for himselfe, there is no  other.\n"
"Love if thee list; for I love and aye shall\n"
"And soothly, leve brother, this is all.\n"
"Here in this prison musten we endure,\n"
"And each of us take his Aventure.\"\n"
"\n"
"Great was the strife and long between these tway,\n"
"If that I hadde leisure for to say;\n"
"But to the effect: it happen'd on a day\n"
"(To tell it you as shortly as I may),\n"
"A worthy duke that hight Perithous<14>\n"
"That fellow was to the Duke Theseus\n"
"Since thilke* day that they were children lite**          *that **little\n"
"Was come to Athens, his fellow to visite,\n"
"And for to play, as he was wont to do;\n"
"For in this world he loved no man so;\n"
"And he lov'd him as tenderly again.\n"
"So well they lov'd, as olde bookes sayn,\n"
"That when that one was dead, soothly to sayn,\n"
"His fellow went and sought him down in hell:\n"
"But of that story list me not to write.\n"
"Duke Perithous loved well Arcite,\n"
"And had him known at Thebes year by year:\n"
"And finally at request and prayere\n"
"Of Perithous, withoute ranson\n"
"Duke Theseus him let out of prison,\n"
"Freely to go, where him list over all,\n"
"In such a guise, as I you tellen shall\n"
"This was the forword*, plainly to indite,                       *promise\n"
"Betwixte Theseus and him Arcite:\n"
"That if so were, that Arcite were y-found\n"
"Ever in his life, by day or night, one stound*               *moment<15>\n"
"In any country of this Theseus,\n"
"And he were caught, it was accorded thus,\n"
"That with a sword he shoulde lose his head;\n"
"There was none other remedy nor rede*.                          *counsel\n"
"But took his leave, and homeward he him sped;\n"
"Let him beware, his necke lieth *to wed*.                    *in pledge*\n"
"\n"
"How great a sorrow suff'reth now Arcite!\n"
"The death he feeleth through his hearte smite;\n"
"He weepeth, waileth, crieth piteously;\n"
"To slay himself he waiteth privily.\n"
"He said; \"Alas the day that I was born!\n"
"Now is my prison worse than beforn:\n"
"*Now is me shape* eternally to dwell                *it is fixed for me*\n"
"Not in purgatory, but right in hell.\n"
"Alas! that ever I knew Perithous.\n"
"For elles had I dwelt with Theseus\n"
"Y-fettered in his prison evermo'.\n"
"Then had I been in bliss, and not in woe.\n"
"Only the sight of her, whom that I serve,\n"
"Though that I never may her grace deserve,\n"
"Would have sufficed right enough for me.\n"
"O deare cousin Palamon,\" quoth he,\n"
"\"Thine is the vict'ry of this aventure,\n"
"Full blissfully in prison to endure:\n"
"In prison? nay certes, in paradise.\n"
"Well hath fortune y-turned thee the dice,\n"
"That hast the sight of her, and I th' absence.\n"
"For possible is, since thou hast her presence,\n"
"And art a knight, a worthy and an able,\n"
"That by some cas*, since fortune is changeable,                  *chance\n"
"Thou may'st to thy desire sometime attain.\n"
"But I that am exiled, and barren\n"
"Of alle grace, and in so great despair,\n"
"That there n'is earthe, water, fire, nor air,\n"
"Nor creature, that of them maked is,\n"
"That may me helpe nor comfort in this,\n"
"Well ought I *sterve in wanhope* and distress.          *die in despair*\n"
"Farewell my life, my lust*, and my gladness.                   *pleasure\n"
"Alas, *why plainen men so in commune       *why do men so often complain\n"
"Of purveyance of God*, or of Fortune,              of God's providence?*\n"
"That giveth them full oft in many a guise\n"
"Well better than they can themselves devise?\n"
"Some man desireth for to have richess,\n"
"That cause is of his murder or great sickness.\n"
"And some man would out of his prison fain,\n"
"That in his house is of his meinie* slain.                *servants <16>\n"
"Infinite harmes be in this mattere.\n"
"We wot never what thing we pray for here.\n"
"We fare as he that drunk is as a mouse.\n"
"A drunken man wot well he hath an house,\n"
"But he wot not which is the right way thither,\n"
"And to a drunken man the way is slither*.                      *slippery\n"
"And certes in this world so fare we.\n"
"We seeke fast after felicity,\n"
"But we go wrong full often truely.\n"
"Thus we may sayen all, and namely* I,                        *especially\n"
"That ween'd*, and had a great opinion,                          *thought\n"
"That if I might escape from prison\n"
"Then had I been in joy and perfect heal,\n"
"Where now I am exiled from my weal.\n"
"Since that I may not see you, Emily,\n"
"I am but dead; there is no remedy.\"\n"
"\n"
"Upon that other side, Palamon,\n"
"When that he wist Arcita was agone,\n"
"Much sorrow maketh, that the greate tower\n"
"Resounded of his yelling and clamour\n"
"The pure* fetters on his shinnes great                        *very <17>\n"
"Were of his bitter salte teares wet.\n"
"\n"
"\"Alas!\" quoth he, \"Arcita, cousin mine,\n"
"Of all our strife, God wot, the fruit is thine.\n"
"Thou walkest now in Thebes at thy large,\n"
"And of my woe thou *givest little charge*.          *takest little heed*\n"
"Thou mayst, since thou hast wisdom and manhead*,       *manhood, courage\n"
"Assemble all the folk of our kindred,\n"
"And make a war so sharp on this country\n"
"That by some aventure, or some treaty,\n"
"Thou mayst have her to lady and to wife,\n"
"For whom that I must needes lose my life.\n"
"For as by way of possibility,\n"
"Since thou art at thy large, of prison free,\n"
"And art a lord, great is thine avantage,\n"
"More than is mine, that sterve here in a cage.\n"
"For I must weep and wail, while that I live,\n"
"With all the woe that prison may me give,\n"
"And eke with pain that love me gives also,\n"
"That doubles all my torment and my woe.\"\n"
"\n"
"Therewith the fire of jealousy upstart\n"
"Within his breast, and hent* him by the heart                    *seized\n"
"So woodly*, that he like was to behold                            *madly\n"
"The box-tree, or the ashes dead and cold.\n"
"Then said; \"O cruel goddess, that govern\n"
"This world with binding of your word etern*                     *eternal\n"
"And writen in the table of adamant\n"
"Your parlement* and your eternal grant,                    *consultation\n"
"What is mankind more *unto you y-hold*                  *by you esteemed\n"
"Than is the sheep, that rouketh* in the fold!      *lie huddled together\n"
"For slain is man, right as another beast;\n"
"And dwelleth eke in prison and arrest,\n"
"And hath sickness, and great adversity,\n"
"And oftentimes guilteless, pardie*                               *by God\n"
"What governance is in your prescience,\n"
"That guilteless tormenteth innocence?\n"
"And yet increaseth this all my penance,\n"
"That man is bounden to his observance\n"
"For Godde's  sake to *letten of his will*,         *restrain his desire*\n"
"Whereas a beast may all his lust fulfil.\n"
"And when a beast is dead, he hath no pain;\n"
"But man after his death must weep and plain,\n"
"Though in this worlde he have care and woe:\n"
"Withoute doubt it maye standen so.\n"
"\"The answer of this leave I to divines,\n"
"But well I wot, that in this world great pine* is;        *pain, trouble\n"
"Alas! I see a serpent or a thief\n"
"That many a true man hath done mischief,\n"
"Go at his large, and where him list may turn.\n"
"But I must be in prison through Saturn,\n"
"And eke through Juno, jealous and eke wood*,                        *mad\n"
"That hath well nigh destroyed all the blood\n"
"Of Thebes, with his waste walles wide.\n"
"And Venus slay'th me on that other side\n"
"For jealousy, and fear of him, Arcite.\"\n"
"\n"
"Now will I stent* of Palamon a lite**,                   *pause **little\n"
"And let him in his prison stille dwell,\n"
"And of Arcita forth I will you tell.\n"
"The summer passeth, and the nightes long\n"
"Increase double-wise the paines strong\n"
"Both of the lover and the prisonere.\n"
"I n'ot* which hath the wofuller mistere**.         *know not **condition\n"
"For, shortly for to say, this Palamon\n"
"Perpetually is damned to prison,\n"
"In chaines and in fetters to be dead;\n"
"And Arcite is exiled *on his head*                *on peril of his head*\n"
"For evermore as out of that country,\n"
"Nor never more he shall his lady see.\n"
"You lovers ask I now this question,<18>\n"
"Who lieth the worse, Arcite or Palamon?\n"
"The one may see his lady day by day,\n"
"But in prison he dwelle must alway.\n"
"The other where him list may ride or go,\n"
"But see his lady shall he never mo'.\n"
"Now deem all as you liste, ye that can,\n"
"For I will tell you forth as I began.\n"
"\n"
"When that Arcite to Thebes comen was,\n"
"Full oft a day he swelt*, and said, \"Alas!\"                     *fainted\n"
"For see this lady he shall never mo'.\n"
"And shortly to concluden all his woe,\n"
"So much sorrow had never creature\n"
"That is or shall be while the world may dure.\n"
"His sleep, his meat, his drink is *him byraft*,    *taken away from him*\n"
"That lean he wex*, and dry as any shaft.                         *became\n"
"His eyen hollow, grisly to behold,\n"
"His hue sallow, and pale as ashes cold,\n"
"And solitary he was, ever alone,\n"
"And wailing all the night, making his moan.\n"
"And if he hearde song or instrument,\n"
"Then would he weepen, he might not be stent*.                   *stopped\n"
"So feeble were his spirits, and so low,\n"
"And changed so, that no man coulde know\n"
"His speech, neither his voice, though men it heard.\n"
"And in his gear* for all the world he far'd              *behaviour <19>\n"
"Not only like the lovers' malady\n"
"Of Eros, but rather y-like manie*                               *madness\n"
"Engender'd of humours melancholic,\n"
"Before his head in his cell fantastic.<20>\n"
"And shortly turned was all upside down,\n"
"Both habit and eke dispositioun,\n"
"Of him, this woful lover Dan* Arcite.                         *Lord <21>\n"
"Why should I all day of his woe indite?\n"
"When he endured had a year or two\n"
"This cruel torment, and this pain and woe,\n"
"At Thebes, in his country, as I said,\n"
"Upon a night in sleep as he him laid,\n"
"Him thought how that the winged god Mercury\n"
"Before him stood, and bade him to be merry.\n"
"His sleepy yard* in hand he bare upright;                      *rod <22>\n"
"A hat he wore upon his haires bright.\n"
"Arrayed was this god (as he took keep*)                          *notice\n"
"As he was when that Argus<23> took his sleep;\n"
"And said him thus: \"To Athens shalt thou wend*;                      *go\n"
"There is thee shapen* of thy woe an end.\"               *fixed, prepared\n"
"And with that word Arcite woke and start.\n"
"\"Now truely how sore that e'er me smart,\"\n"
"Quoth he, \"to Athens right now will I fare.\n"
"Nor for no dread of death shall I not spare\n"
"To see my lady that I love and serve;\n"
"In her presence *I recke not to sterve.*\"         *do not care if I die*\n"
"And with that word he caught a great mirror,\n"
"And saw that changed was all his colour,\n"
"And saw his visage all in other kind.\n"
"And right anon it ran him ill his mind,\n"
"That since his face was so disfigur'd\n"
"Of malady the which he had endur'd,\n"
"He mighte well, if that he *bare him low,*      *lived in lowly fashion*\n"
"Live in Athenes evermore unknow,\n"
"And see his lady wellnigh day by day.\n"
"And right anon he changed his array,\n"
"And clad him as a poore labourer.\n"
"And all alone, save only a squier,\n"
"That knew his privity* and all his cas**,             *secrets **fortune\n"
"Which was disguised poorly as he was,\n"
"To Athens is he gone the nexte*  way.                      *nearest <24>\n"
"And to the court he went upon a day,\n"
"And at the gate he proffer'd his service,\n"
"To drudge and draw, what so men would devise*.                    *order\n"
"And, shortly of this matter for to sayn,\n"
"He fell in office with a chamberlain,\n"
"The which that dwelling was with Emily.\n"
"For he was wise, and coulde soon espy\n"
"Of every servant which that served her.\n"
"Well could he hewe wood, and water bear,\n"
"For he was young and mighty for the nones*,                    *occasion\n"
"And thereto he was strong and big of bones\n"
"To do that any wight can him devise.\n"
"\n"
"A year or two he was in this service,\n"
"Page of the chamber of Emily the bright;\n"
"And Philostrate he saide that he hight.\n"
"But half so well belov'd a man as he\n"
"Ne was there never in court of his degree.\n"
"He was so gentle of conditioun,\n"
"That throughout all the court was his renown.\n"
"They saide that it were a charity\n"
"That Theseus would *enhance his degree*,           *elevate him in rank*\n"
"And put him in some worshipful service,\n"
"There as he might his virtue exercise.\n"
"And thus within a while his name sprung\n"
"Both of his deedes, and of his good tongue,\n"
"That Theseus hath taken him so near,\n"
"That of his chamber he hath made him squire,\n"
"And gave him gold to maintain his degree;\n"
"And eke men brought him out of his country\n"
"From year to year full privily his rent.\n"
"But honestly and slyly* he it spent,              *discreetly, prudently\n"
"That no man wonder'd how that he it had.\n"
"And three year in this wise his life be lad*,                       *led\n"
"And bare him so in peace and eke in werre*,                         *war\n"
"There was no man that Theseus had so derre*.                       *dear\n"
"And in this blisse leave I now Arcite,\n"
"And speak I will of Palamon a lite*.                             *little\n"
"\n"
"In darkness horrible, and strong prison,\n"
"This seven year hath sitten Palamon,\n"
"Forpined*, what for love, and for distress.          *pined, wasted away\n"
"Who feeleth double sorrow and heaviness\n"
"But Palamon? that love distraineth* so,                        *afflicts\n"
"That wood* out of his wits he went for woe,                         *mad\n"
"And eke thereto he is a prisonere\n"
"Perpetual, not only for a year.\n"
"Who coulde rhyme in English properly\n"
"His martyrdom? forsooth*, it is not I;                            *truly\n"
"Therefore I pass as lightly as I may.\n"
"It fell that in the seventh year, in May\n"
"The thirde night (as olde bookes sayn,\n"
"That all this story tellen more plain),\n"
"Were it by a venture or destiny\n"
"(As when a thing is shapen* it shall be),              *settled, decreed\n"
"That soon after the midnight, Palamon\n"
"By helping of a friend brake his prison,\n"
"And fled the city fast as he might go,\n"
"For he had given drink his gaoler so\n"
"Of a clary <25>, made of a certain wine,\n"
"With *narcotise and opie* of Thebes fine,          *narcotics and opium*\n"
"That all the night, though that men would him shake,\n"
"The gaoler slept, he mighte not awake:\n"
"And thus he fled as fast as ever he may.\n"
"The night was short, and *faste by the day            *close at hand was\n"
"That needes cast he must himself to hide*.          the day during which\n"
"And to a grove faste there beside       he must cast about, or contrive,\n"
"With dreadful foot then stalked Palamon.            to conceal himself.*\n"
"For shortly this was his opinion,\n"
"That in the grove he would him hide all day,\n"
"And in the night then would he take his way\n"
"To Thebes-ward, his friendes for to pray\n"
"On Theseus to help him to warray*.                        *make war <26>\n"
"And shortly either he would lose his life,\n"
"Or winnen Emily unto his wife.\n"
"This is th' effect, and his intention plain.\n"
"\n"
"Now will I turn to Arcita again,\n"
"That little wist how nighe was his care,\n"
"Till that Fortune had brought him in the snare.\n"
"The busy lark, the messenger of day,\n"
"Saluteth in her song the morning gray;\n"
"And fiery Phoebus riseth up so bright,\n"
"That all the orient laugheth at the sight,\n"
"And with his streames* drieth in the greves**             *rays **groves\n"
"The silver droppes, hanging on the leaves;\n"
"And Arcite, that is in the court royal\n"
"With Theseus, his squier principal,\n"
"Is ris'n, and looketh on the merry day.\n"
"And for to do his observance to May,\n"
"Remembering the point* of his desire,                            *object\n"
"He on his courser, starting as the fire,\n"
"Is ridden to the fieldes him to play,\n"
"Out of the court, were it a mile or tway.\n"
"And to the grove, of which I have you told,\n"
"By a venture his way began to hold,\n"
"To make him a garland of the greves*,                            *groves\n"
"Were it of woodbine, or of hawthorn leaves,\n"
"And loud he sang against the sun so sheen*.              *shining bright\n"
"\"O May, with all thy flowers and thy green,\n"
"Right welcome be thou, faire freshe May,\n"
"I hope that I some green here getten may.\"\n"
"And from his courser*, with a lusty heart,                        *horse\n"
"Into the grove full hastily he start,\n"
"And in a path he roamed up and down,\n"
"There as by aventure this Palamon\n"
"Was in a bush, that no man might him see,\n"
"For sore afeard of his death was he.\n"
"Nothing ne knew he that it was Arcite;\n"
"God wot he would have *trowed it full lite*.   *full little believed it*\n"
"But sooth is said, gone since full many years,\n"
"The field hath eyen*, and the wood hath ears,                      *eyes\n"
"It is full fair a man *to bear him even*,           *to be on his guard*\n"
"For all day meeten men at *unset steven*.          *unexpected time <27>\n"
"Full little wot Arcite of his fellaw,\n"
"That was so nigh to hearken of his saw*,                 *saying, speech\n"
"For in the bush he sitteth now full still.\n"
"When that Arcite had roamed all his fill,\n"
"And *sungen all the roundel* lustily,           *sang the roundelay*<28>\n"
"Into a study he fell suddenly,\n"
"As do those lovers in their *quainte gears*,              *odd fashions*\n"
"Now in the crop*, and now down in the breres**, <29>           *tree-top\n"
"Now up, now down, as bucket in a well.                          **briars\n"
"Right as the Friday, soothly for to tell,\n"
"Now shineth it, and now it raineth fast,\n"
"Right so can geary* Venus overcast                            *changeful\n"
"The heartes of her folk, right as her day\n"
"Is gearful*, right so changeth she array.                     *changeful\n"
"Seldom is Friday all the weeke like.\n"
"When Arcite had y-sung, he gan to sike*,                           *sigh\n"
"And sat him down withouten any more:\n"
"\"Alas!\" quoth he, \"the day that I was bore!\n"
"How longe, Juno, through thy cruelty\n"
"Wilt thou warrayen* Thebes the city?                            *torment\n"
"Alas! y-brought is to confusion\n"
"The blood royal of Cadm' and Amphion:\n"
"Of Cadmus, which that was the firste man,\n"
};
prog_char knightsTale2[] PROGMEM= {
"That Thebes built, or first the town began,\n"
"And of the city first was crowned king.\n"
"Of his lineage am I, and his offspring\n"
"By very line, as of the stock royal;\n"
"And now I am *so caitiff and so thrall*,         *wretched and enslaved*\n"
"That he that is my mortal enemy,\n"
"I serve him as his squier poorely.\n"
"And yet doth Juno me well more shame,\n"
"For I dare not beknow* mine owen name,                 *acknowledge <30>\n"
"But there as I was wont to hight Arcite,\n"
"Now hight I Philostrate, not worth a mite.\n"
"Alas! thou fell Mars, and alas! Juno,\n"
"Thus hath your ire our lineage all fordo*                *undone, ruined\n"
"Save only me, and wretched Palamon,\n"
"That Theseus martyreth in prison.\n"
"And over all this, to slay me utterly,\n"
"Love hath his fiery dart so brenningly*                       *burningly\n"
"Y-sticked through my true careful heart,\n"
"That shapen was my death erst than my shert. <31>\n"
"Ye slay me with your eyen, Emily;\n"
"Ye be the cause wherefore that I die.\n"
"Of all the remnant of mine other care\n"
"Ne set I not the *mountance of a tare*,               *value of a straw*\n"
"So that I could do aught to your pleasance.\"\n"
"\n"
"And with that word he fell down in a trance\n"
"A longe time; and afterward upstart\n"
"This Palamon, that thought thorough his heart\n"
"He felt a cold sword suddenly to glide:\n"
"For ire he quoke*, no longer would he hide.                      *quaked\n"
"And when that he had heard Arcite's tale,\n"
"As he were wood*, with face dead and pale,                          *mad\n"
"He start him up out of the bushes thick,\n"
"And said: \"False Arcita, false traitor wick'*,                   *wicked\n"
"Now art thou hent*, that lov'st my lady so,                      *caught\n"
"For whom that I have all this pain and woe,\n"
"And art my blood, and to my counsel sworn,\n"
"As I full oft have told thee herebeforn,\n"
"And hast bejaped* here Duke Theseus,             *deceived, imposed upon\n"
"And falsely changed hast thy name thus;\n"
"I will be dead, or elles thou shalt die.\n"
"Thou shalt not love my lady Emily,\n"
"But I will love her only and no mo';\n"
"For I am Palamon thy mortal foe.\n"
"And though I have no weapon in this place,\n"
"But out of prison am astart* by grace,                          *escaped\n"
"I dreade* not that either thou shalt die,                         *doubt\n"
"Or else thou shalt not loven Emily.\n"
"Choose which thou wilt, for thou shalt not astart.\"\n"
"\n"
"This Arcite then, with full dispiteous* heart,                 *wrathful\n"
"When he him knew, and had his tale heard,\n"
"As fierce as lion pulled out a swerd,\n"
"And saide thus; \"By God that sitt'th above,\n"
"*N'ere it* that thou art sick, and wood for love,          *were it not*\n"
"And eke that thou no weap'n hast in this place,\n"
"Thou should'st never out of this grove pace,\n"
"That thou ne shouldest dien of mine hand.\n"
"For I defy the surety and the band,\n"
"Which that thou sayest I have made to thee.\n"
"What? very fool, think well that love is free;\n"
"And I will love her maugre* all thy might.                      *despite\n"
"But, for thou art a worthy gentle knight,\n"
"And *wilnest to darraine her by bataille*,             *will reclaim her\n"
"Have here my troth, to-morrow I will not fail,                by combat*\n"
"Without weeting* of any other wight,                          *knowledge\n"
"That here I will be founden as a knight,\n"
"And bringe harness* right enough for thee;              *armour and arms\n"
"And choose the best, and leave the worst for me.\n"
"And meat and drinke this night will I bring\n"
"Enough for thee, and clothes for thy bedding.\n"
"And if so be that thou my lady win,\n"
"And slay me in this wood that I am in,\n"
"Thou may'st well have thy lady as for me.\"\n"
"This Palamon answer'd, \"I grant it thee.\"\n"
"And thus they be departed till the morrow,\n"
"When each of them hath *laid his faith to borrow*.   *pledged his faith*\n"
"\n"
"O Cupid, out of alle charity!\n"
"O Regne* that wilt no fellow have with thee!                 *queen <32>\n"
"Full sooth is said, that love nor lordeship\n"
"Will not, *his thanks*, have any fellowship.             *thanks to him*\n"
"Well finden that Arcite and Palamon.\n"
"Arcite is ridd anon unto the town,\n"
"And on the morrow, ere it were daylight,\n"
"Full privily two harness hath he dight*,                       *prepared\n"
"Both suffisant and meete to darraine*                           *contest\n"
"The battle in the field betwixt them twain.\n"
"And on his horse, alone as he was born,\n"
"He carrieth all this harness him beforn;\n"
"And in the grove, at time and place y-set,\n"
"This Arcite and this Palamon be met.\n"
"Then change gan the colour of their face;\n"
"Right as the hunter in the regne* of Thrace                     *kingdom\n"
"That standeth at a gappe with a spear\n"
"When hunted is the lion or the bear,\n"
"And heareth him come rushing in the greves*,                     *groves\n"
"And breaking both the boughes and the leaves,\n"
"Thinketh, \"Here comes my mortal enemy,\n"
"Withoute fail, he must be dead or I;\n"
"For either I must slay him at the gap;\n"
"Or he must slay me, if that me mishap:\"\n"
"So fared they, in changing of their hue\n"
"*As far as either of them other knew*.        *When they recognised each\n"
"There was no good day, and no saluting,                  other afar off*\n"
"But straight, withoute wordes rehearsing,\n"
"Evereach of them holp to arm the other,\n"
"As friendly, as he were his owen brother.\n"
"And after that, with sharpe speares strong\n"
"They foined* each at other wonder long.                          *thrust\n"
"Thou mightest weene*, that this Palamon                           *think\n"
"In fighting were as a wood* lion,                                   *mad\n"
"And as a cruel tiger was Arcite:\n"
"As wilde boars gan they together smite,\n"
"That froth as white as foam, *for ire wood*.            *mad with anger*\n"
"Up to the ancle fought they in their blood.\n"
"And in this wise I let them fighting dwell,\n"
"And forth I will of Theseus you tell.\n"
"\n"
"The Destiny, minister general,\n"
"That executeth in the world o'er all\n"
"The purveyance*, that God hath seen beforn;              *foreordination\n"
"So strong it is, that though the world had sworn\n"
"The contrary of a thing by yea or nay,\n"
"Yet some time it shall fallen on a day\n"
"That falleth not eft* in a thousand year.                         *again\n"
"For certainly our appetites here,\n"
"Be it of war, or peace, or hate, or love,\n"
"All is this ruled by the sight* above.         *eye, intelligence, power\n"
"This mean I now by mighty Theseus,\n"
"That for to hunten is so desirous --\n"
"And namely* the greate hart in May --                        *especially\n"
"That in his bed there dawneth him no day\n"
"That he n'is clad, and ready for to ride\n"
"With hunt and horn, and houndes him beside.\n"
"For in his hunting hath he such delight,\n"
"That it is all his joy and appetite\n"
"To be himself the greate harte's bane*                      *destruction\n"
"For after Mars he serveth now Diane.\n"
"Clear was the day, as I have told ere this,\n"
"And Theseus, with alle joy and bliss,\n"
"With his Hippolyta, the faire queen,\n"
"And Emily, y-clothed all in green,\n"
"On hunting be they ridden royally.\n"
"And to the grove, that stood there faste by,\n"
"In which there was an hart, as men him told,\n"
"Duke Theseus the straighte way doth hold,\n"
"And to the laund* he rideth him full right,                  *plain <33>\n"
"There was the hart y-wont to have his flight,\n"
"And over a brook, and so forth on his way.\n"
"This Duke will have a course at him or tway\n"
"With houndes, such as him lust* to command.                     *pleased\n"
"And when this Duke was come to the laund,\n"
"Under the sun he looked, and anon\n"
"He was ware of Arcite and Palamon,\n"
"That foughte breme*, as it were bulles two.                    *fiercely\n"
"The brighte swordes wente to and fro\n"
"So hideously, that with the leaste stroke\n"
"It seemed that it woulde fell an oak,\n"
"But what they were, nothing yet he wote*.                          *knew\n"
"This Duke his courser with his spurres smote,\n"
"*And at a start* he was betwixt them two,                     *suddenly*\n"
"And pulled out a sword and cried, \"Ho!\n"
"No more, on pain of losing of your head.\n"
"By mighty Mars, he shall anon be dead\n"
"That smiteth any stroke, that I may see!\n"
"But tell to me what mister* men ye be,                *manner, kind <34>\n"
"That be so hardy for to fighte here\n"
"Withoute judge or other officer,\n"
"As though it were in listes royally. <35>\n"
"This Palamon answered hastily,\n"
"And saide: \"Sir, what needeth wordes mo'?\n"
"We have the death deserved bothe two,\n"
"Two woful wretches be we, and caitives,\n"
"That be accumbered* of our own lives,                          *burdened\n"
"And as thou art a rightful lord and judge,\n"
"So give us neither mercy nor refuge.\n"
"And slay me first, for sainte charity,\n"
"But slay my fellow eke as well as me.\n"
"Or slay him first; for, though thou know it lite*,               *little\n"
"This is thy mortal foe, this is Arcite\n"
"That from thy land is banisht on his head,\n"
"For which he hath deserved to be dead.\n"
"For this is he that came unto thy gate\n"
"And saide, that he highte Philostrate.\n"
"Thus hath he japed* thee full many year,                       *deceived\n"
"And thou hast made of him thy chief esquier;\n"
"And this is he, that loveth Emily.\n"
"For since the day is come that I shall die\n"
"I make pleinly* my confession,                      *fully, unreservedly\n"
"That I am thilke* woful Palamon,                         *that same <36>\n"
"That hath thy prison broken wickedly.\n"
"I am thy mortal foe, and it am I\n"
"That so hot loveth Emily the bright,\n"
"That I would die here present in her sight.\n"
"Therefore I aske death and my jewise*.                        *judgement\n"
"But slay my fellow eke in the same wise,\n"
"For both we have deserved to be slain.\"\n"
"\n"
"This worthy Duke answer'd anon again,\n"
"And said, \"This is a short conclusion.\n"
"Your own mouth, by your own confession\n"
"Hath damned you, and I will it record;\n"
"It needeth not to pain you with the cord;\n"
"Ye shall be dead, by mighty Mars the Red.<37>\n"
"\n"
"The queen anon for very womanhead\n"
"Began to weep, and so did Emily,\n"
"And all the ladies in the company.\n"
"Great pity was it as it thought them all,\n"
"That ever such a chance should befall,\n"
"For gentle men they were, of great estate,\n"
"And nothing but for love was this debate\n"
"They saw their bloody woundes wide and sore,\n"
"And cried all at once, both less and more,\n"
"\"Have mercy, Lord, upon us women all.\"\n"
"And on their bare knees adown they fall\n"
"And would have kissed his feet there as he stood,\n"
"Till at the last *aslaked was his mood*                   *his anger was\n"
"(For pity runneth soon in gentle heart);                       appeased*\n"
"And though at first for ire he quoke and start\n"
"He hath consider'd shortly in a clause\n"
"The trespass of them both, and eke the cause:\n"
"And although that his ire their guilt accused\n"
"Yet in his reason he them both excused;\n"
"As thus; he thoughte well that every man\n"
"Will help himself in love if that he can,\n"
"And eke deliver himself out of prison.\n"
"Of women, for they wepten ever-in-one:*                     *continually\n"
"And eke his hearte had compassion\n"
"And in his gentle heart he thought anon,\n"
"And soft unto himself he saide: \"Fie\n"
"Upon a lord that will have no mercy,\n"
"But be a lion both in word and deed,\n"
"To them that be in repentance and dread,\n"
"As well as-to a proud dispiteous* man                         *unpitying\n"
"That will maintaine what he first began.\n"
"That lord hath little of discretion,\n"
"That in such case *can no division*:           *can make no distinction*\n"
"But weigheth pride and humbless *after one*.\"                    *alike*\n"
"And shortly, when his ire is thus agone,\n"
"He gan to look on them with eyen light*,               *gentle, lenient*\n"
"And spake these same wordes *all on height.*                     *aloud*\n"
"\n"
"\"The god of love, ah! benedicite*,                         *bless ye him\n"
"How mighty and how great a lord is he!\n"
"Against his might there gaine* none obstacles,           *avail, conquer\n"
"He may be called a god for his miracles\n"
"For he can maken at his owen guise\n"
"Of every heart, as that him list devise.\n"
"Lo here this Arcite, and this Palamon,\n"
"That quietly were out of my prison,\n"
"And might have lived in Thebes royally,\n"
"And weet* I am their mortal enemy,                                 *knew\n"
"And that their death li'th in my might also,\n"
"And yet hath love, *maugre their eyen two*,     *in spite of their eyes*\n"
"Y-brought them hither bothe for to die.\n"
"Now look ye, is not this an high folly?\n"
"Who may not be a fool, if but he love?\n"
"Behold, for Godde's sake that sits above,\n"
"See how they bleed! be they not well array'd?\n"
"Thus hath their lord, the god of love, them paid\n"
"Their wages and their fees for their service;\n"
"And yet they weene for to be full wise,\n"
"That serve love, for aught that may befall.\n"
"But this is yet the beste game* of all,                            *joke\n"
"That she, for whom they have this jealousy,\n"
"Can them therefor as muchel thank as me.\n"
"She wot no more of all this *hote fare*,                 *hot behaviour*\n"
"By God, than wot a cuckoo or an hare.\n"
"But all must be assayed hot or cold;\n"
"A man must be a fool, or young or old;\n"
"I wot it by myself *full yore agone*:                   *long years ago*\n"
"For in my time a servant was I one.\n"
"And therefore since I know of love's pain,\n"
"And wot how sore it can a man distrain*,                       *distress\n"
"As he that oft hath been caught in his last*,                *snare <38>\n"
"I you forgive wholly this trespass,\n"
"At request of the queen that kneeleth here,\n"
"And eke of Emily, my sister dear.\n"
"And ye shall both anon unto me swear,\n"
"That never more ye shall my country dere*                        *injure\n"
"Nor make war upon me night nor day,\n"
"But be my friends in alle that ye may.\n"
"I you forgive this trespass *every deal*.                   *completely*\n"
"And they him sware *his asking* fair and well,           *what he asked*\n"
"And him of lordship and of mercy pray'd,\n"
"And he them granted grace, and thus he said:\n"
"\n"
"\"To speak of royal lineage and richess,\n"
"Though that she were a queen or a princess,\n"
"Each of you both is worthy doubteless\n"
"To wedde when time is; but natheless\n"
"I speak as for my sister Emily,\n"
"For whom ye have this strife and jealousy,\n"
"Ye wot* yourselves, she may not wed the two                        *know\n"
"At once, although ye fight for evermo:\n"
"But one of you, *all be him loth or lief,*    *whether or not he wishes*\n"
"He must *go pipe into an ivy leaf*:                       *\"go whistle\"*\n"
"This is to say, she may not have you both,\n"
"All be ye never so jealous, nor so wroth.\n"
"And therefore I you put in this degree,\n"
"That each of you shall have his destiny\n"
"As *him is shape*; and hearken in what wise      *as is decreed for him*\n"
"Lo hear your end of that I shall devise.\n"
"My will is this, for plain conclusion\n"
"Withouten any replication*,                                       *reply\n"
"If that you liketh, take it for the best,\n"
"That evereach of you shall go where *him lest*,              *he pleases\n"
"Freely without ransom or danger;\n"
"And this day fifty weekes, *farre ne nerre*,     *neither more nor less*\n"
"Evereach of you shall bring an hundred knights,\n"
"Armed for listes up at alle rights\n"
"All ready to darraine* her by bataille,                     *contend for\n"
"And this behete* I you withoute fail                            *promise\n"
"Upon my troth, and as I am a knight,\n"
"That whether of you bothe that hath might,\n"
"That is to say, that whether he or thou\n"
"May with his hundred, as I spake of now,\n"
"Slay his contrary, or out of listes drive,\n"
"Him shall I given Emily to wive,\n"
"To whom that fortune gives so fair a grace.\n"
"The listes shall I make here in this place.\n"
"*And God so wisly on my soule rue*,              *may God as surely have\n"
"As I shall even judge be and true.                     mercy on my soul*\n"
"Ye shall none other ende with me maken\n"
"Than one of you shalle be dead or taken.\n"
"And if you thinketh this is well y-said,\n"
"Say your advice*, and hold yourselves apaid**.      *opinion **satisfied\n"
"This is your end, and your conclusion.\"\n"
"Who looketh lightly now but Palamon?\n"
"Who springeth up for joye but Arcite?\n"
"Who could it tell, or who could it indite,\n"
"The joye that is maked in the place\n"
"When Theseus hath done so fair a grace?\n"
"But down on knees went every *manner wight*,            *kind of person*\n"
"And thanked him with all their heartes' might,\n"
"And namely* these Thebans *ofte sithe*.         *especially *oftentimes*\n"
"And thus with good hope and with hearte blithe\n"
"They take their leave, and homeward gan they ride\n"
"To Thebes-ward, with his old walles wide.\n"
"\n"
"I trow men woulde deem it negligence,\n"
"If I forgot to telle the dispence*                          *expenditure\n"
"Of Theseus, that went so busily\n"
"To maken up the listes royally,\n"
"That such a noble theatre as it was,\n"
"I dare well say, in all this world there n'as*.                 *was not\n"
"The circuit a mile was about,\n"
"Walled of stone, and ditched all without.\n"
"*Round was the shape, in manner of compass,\n"
"Full of degrees, the height of sixty pas*               *see note  <39>*\n"
"That when a man was set on one degree\n"
"He letted* not his fellow for to see.                          *hindered\n"
"Eastward there stood a gate of marble white,\n"
"Westward right such another opposite.\n"
"And, shortly to conclude, such a place\n"
"Was never on earth made in so little space,\n"
"For in the land there was no craftes-man,\n"
"That geometry or arsmetrike* can**,                   *arithmetic **knew\n"
"Nor pourtrayor*, nor carver of images,                 *portrait painter\n"
"That Theseus ne gave him meat and wages\n"
"The theatre to make and to devise.\n"
"And for to do his rite and sacrifice\n"
"He eastward hath upon the gate above,\n"
"In worship of Venus, goddess of love,\n"
"*Done make* an altar and an oratory;                 *caused to be made*\n"
"And westward, in the mind and in memory\n"
"Of Mars, he maked hath right such another,\n"
"That coste largely of gold a fother*.                    *a great amount\n"
"And northward, in a turret on the wall,\n"
"Of alabaster white and red coral\n"
"An oratory riche for to see,\n"
"In worship of Diane of chastity,\n"
"Hath Theseus done work in noble wise.\n"
"But yet had I forgotten to devise*                             *describe\n"
"The noble carving, and the portraitures,\n"
"The shape, the countenance of the figures\n"
"That weren in there oratories three.\n"
"\n"
"First in the temple of Venus may'st thou see\n"
"Wrought on the wall,  full piteous to behold,\n"
"The broken sleepes, and the sikes* cold,                         *sighes\n"
"The sacred teares, and the waimentings*,                     *lamentings\n"
"The fiery strokes of the desirings,\n"
"That Love's servants in this life endure;\n"
"The oathes, that their covenants assure.\n"
"Pleasance and Hope, Desire, Foolhardiness,\n"
"Beauty and Youth, and Bawdry and Richess,\n"
"Charms and Sorc'ry, Leasings* and Flattery,                  *falsehoods\n"
"Dispence, Business, and Jealousy,\n"
"That wore of yellow goldes* a garland,                  *sunflowers <40>\n"
"And had a cuckoo sitting on her hand,\n"
"Feasts, instruments, and caroles and dances,\n"
"Lust and array, and all the circumstances\n"
"Of Love, which I reckon'd and reckon shall\n"
"In order, were painted on the wall,\n"
"And more than I can make of mention.\n"
"For soothly all the mount of Citheron,<41>\n"
"Where Venus hath her principal dwelling,\n"
"Was showed on the wall in pourtraying,\n"
"With all the garden, and the lustiness*.                   *pleasantness\n"
"Nor was forgot the porter Idleness,\n"
"Nor Narcissus the fair of *yore agone*,                    *olden times*\n"
"Nor yet the folly of King Solomon,\n"
"Nor yet the greate strength of Hercules,\n"
"Th' enchantments of Medea and Circes,\n"
"Nor of Turnus the hardy fierce courage,\n"
"The rich Croesus *caitif in servage.* <42>         *abased into slavery*\n"
"Thus may ye see, that wisdom nor richess,\n"
"Beauty, nor sleight, nor strength, nor hardiness\n"
"Ne may with Venus holde champartie*,            *divided possession <43>\n"
"For as her liste the world may she gie*.                          *guide\n"
"Lo, all these folk so caught were in her las*                     *snare\n"
"Till they for woe full often said, Alas!\n"
"Suffice these ensamples one or two,\n"
"Although I could reckon a thousand mo'.\n"
"\n"
"The statue of Venus, glorious to see\n"
"Was naked floating in the large sea,\n"
"And from the navel down all cover'd was\n"
"With waves green, and bright as any glass.\n"
"A citole <44> in her right hand hadde she,\n"
"And on her head, full seemly for to see,\n"
"A rose garland fresh, and well smelling,\n"
"Above her head her doves flickering\n"
"Before her stood her sone Cupido,\n"
"Upon his shoulders winges had he two;\n"
"And blind he was, as it is often seen;\n"
"A bow he bare, and arrows bright and keen.\n"
"\n"
"Why should I not as well eke tell you all\n"
"The portraiture, that was upon the wall\n"
"Within the temple of mighty Mars the Red?\n"
"All painted was the wall in length and brede*                   *breadth\n"
"Like to the estres* of the grisly place               *interior chambers\n"
"That hight the great temple of Mars in Thrace,\n"
"In thilke* cold and frosty region,                                 *that\n"
"There as Mars hath his sovereign mansion.\n"
"In which there dwelled neither man nor beast,\n"
"With knotty gnarry* barren trees old                            *gnarled\n"
"Of stubbes sharp and hideous to behold;\n"
"In which there ran a rumble and a sough*,                *groaning noise\n"
"As though a storm should bursten every bough:\n"
"And downward from an hill under a bent*                           *slope\n"
"There stood the temple of Mars Armipotent,\n"
"Wrought all of burnish'd steel, of which th' entry\n"
"Was long and strait, and ghastly for to see.\n"
"And thereout came *a rage and such a vise*,       *such a furious voice*\n"
"That it made all the gates for to rise.\n"
"The northern light in at the doore shone,\n"
"For window on the walle was there none\n"
"Through which men mighten any light discern.\n"
"The doors were all of adamant etern,\n"
"Y-clenched *overthwart and ende-long*         *crossways and lengthways*\n"
"With iron tough, and, for to make it strong,\n"
"Every pillar the temple to sustain\n"
"Was tunne-great*, of iron bright and sheen.     *thick as a tun (barrel)\n"
"There saw I first the dark imagining\n"
"Of felony, and all the compassing;\n"
"The cruel ire, as red as any glede*,                          *live coal\n"
"The picke-purse<45>, and eke the pale dread;\n"
"The smiler with the knife under the cloak,\n"
"The shepen* burning with the blacke smoke                   *stable <46>\n"
"The treason of the murd'ring in the bed,\n"
"The open war, with woundes all be-bled;\n"
"Conteke* with bloody knife, and sharp menace.       *contention, discord\n"
"All full of chirking* was that sorry place.     *creaking, jarring noise\n"
"The slayer of himself eke saw I there,\n"
"His hearte-blood had bathed all his hair:\n"
"The nail y-driven in the shode* at night,         *hair of the head <47>\n"
"The colde death, with mouth gaping upright.\n"
"Amiddes of the temple sat Mischance,\n"
"With discomfort and sorry countenance;\n"
"Eke saw I Woodness* laughing in his rage,                       *Madness\n"
"Armed Complaint, Outhees*, and fierce Outrage;                   *Outcry\n"
"The carrain* in the bush, with throat y-corve**,       *corpse **slashed\n"
"A thousand slain, and not *of qualm y-storve*;        *dead of sickness*\n"
"The tyrant, with the prey by force y-reft;\n"
"The town destroy'd, that there was nothing left.\n"
"Yet saw I brent* the shippes hoppesteres, <48>                    *burnt\n"
"The hunter strangled with the wilde bears:\n"
"The sow freting* the child right in the cradle;          *devouring <49>\n"
"The cook scalded, for all his longe ladle.\n"
"Nor was forgot, *by th'infortune of Mart*        *through the misfortune\n"
"The carter overridden with his cart;                             of war*\n"
"Under the wheel full low he lay adown.\n"
"There were also of Mars' division,\n"
"The armourer, the bowyer*, and the smith,                 *maker of bows\n"
"That forgeth sharp swordes on his stith*.                         *anvil\n"
"And all above depainted in a tower\n"
"Saw I Conquest, sitting in great honour,\n"
"With thilke* sharpe sword over his head                            *that\n"
"Hanging by a subtle y-twined thread.\n"
"Painted the slaughter was of Julius<50>,\n"
"Of cruel Nero, and Antonius:\n"
"Although at that time they were yet unborn,\n"
"Yet was their death depainted there beforn,\n"
"By menacing of Mars, right by figure,\n"
"So was it showed in that portraiture,\n"
"As is depainted in the stars above,\n"
"Who shall be slain, or elles dead for love.\n"
"Sufficeth one ensample in stories old,\n"
"I may not reckon them all, though I wo'ld.\n"
"\n"
"The statue of Mars upon a carte* stood                          *chariot\n"
"Armed, and looked grim as he were wood*,                            *mad\n"
"And over his head there shone two figures\n"
"Of starres, that be cleped in scriptures,\n"
"That one Puella, that other Rubeus. <51>\n"
"This god of armes was arrayed thus:\n"
"A wolf there stood before him at his feet\n"
"With eyen red, and of a man he eat:\n"
"With subtle pencil painted was this story,\n"
"In redouting* of Mars and of his glory.                 *reverance, fear\n"
"\n"
"Now to the temple of Dian the chaste\n"
"As shortly as I can I will me haste,\n"
"To telle you all the descriptioun.\n"
"Depainted be the walles up and down\n"
"Of hunting and of shamefast chastity.\n"
"There saw I how woful Calistope,<52>\n"
"When that Dian aggrieved was with her,\n"
"Was turned from a woman to a bear,\n"
"And after was she made the lodestar*:                         *pole star\n"
"Thus was it painted, I can say no far*;                         *farther\n"
"Her son is eke a star as men may see.\n"
"There saw I Dane <53> turn'd into a tree,\n"
"I meane not the goddess Diane,\n"
"But Peneus' daughter, which that hight Dane.\n"
"There saw I Actaeon an hart y-maked*,                              *made\n"
"For vengeance that he saw Dian all naked:\n"
"I saw how that his houndes have him caught,\n"
"And freten* him, for that they knew him not.                     *devour\n"
"Yet painted was, a little farthermore\n"
"How Atalanta hunted the wild boar;\n"
"And Meleager, and many other mo',\n"
"For which Diana wrought them care and woe.\n"
"There saw I many another wondrous story,\n"
"The which me list not drawen to memory.\n"
"This goddess on an hart full high was set*,                      *seated\n"
"With smalle houndes all about her feet,\n"
"And underneath her feet she had a moon,\n"
"Waxing it was, and shoulde wane soon.\n"
"In gaudy green her statue clothed was,\n"
"With bow in hand, and arrows in a case*.                         *quiver\n"
"Her eyen caste she full low adown,\n"
"Where Pluto hath his darke regioun.\n"
"A woman travailing was her beforn,\n"
"But, for her child so longe was unborn,\n"
"Full piteously Lucina <54> gan she call,\n"
"And saide; \"Help, for thou may'st best of all.\"\n"
"Well could he painte lifelike that it wrought;\n"
"With many a florin he the hues had bought.\n"
"Now be these listes made, and Theseus,\n"
"That at his greate cost arrayed thus\n"
"The temples, and the theatre every deal*,                     *part <55>\n"
"When it was done, him liked wonder well.\n"
"\n"
"But stint* I will of Theseus a lite**,          *cease speaking **little\n"
"And speak of Palamon and of Arcite.\n"
"The day approacheth of their returning,\n"
"That evereach an hundred knights should bring,\n"
"The battle to darraine* as I you told;                          *contest\n"
"And to Athens, their covenant to hold,\n"
"Hath ev'reach of them brought an hundred knights,\n"
"Well-armed for the war at alle rights.\n"
"And sickerly* there trowed** many a man,         *surely <56> **believed\n"
"That never, sithen* that the world began,                         *since\n"
"For to speaken of knighthood of their hand,\n"
"As far as God hath maked sea and land,\n"
"Was, of so few, so noble a company.\n"
"For every wight that loved chivalry,\n"
"And would, *his thankes, have a passant name*,        *thanks to his own\n"
"Had prayed, that he might be of that game,               efforts, have a\n"
"And well was him, that thereto chosen was.              surpassing name*\n"
"For if there fell to-morrow such a case,\n"
"Ye knowe well, that every lusty knight,\n"
"That loveth par amour, and hath his might\n"
"Were it in Engleland, or elleswhere,\n"
"They would, their thankes, willen to be there,\n"
"T' fight for a lady; Benedicite,\n"
"It were a lusty* sighte for to see.                            *pleasing\n"
"And right so fared they with Palamon;\n"
"With him there wente knightes many one.\n"
"Some will be armed in an habergeon,\n"
"And in a breast-plate, and in a gipon*;                  *short doublet.\n"
"And some will have *a pair of plates* large;     *back and front armour*\n"
"And some will have a Prusse* shield, or targe;                 *Prussian\n"
"Some will be armed on their legges weel;\n"
"Some have an axe, and some a mace of steel.\n"
};

void setup() {
  int i=0;
  uint8_t c;
  Serial.begin(9600);
  do {
    c = pgm_read_byte(knightsTale+i);
    if (c) Serial.print(c,BYTE);
    i++;
  } while (c);
  do {
    c = pgm_read_byte(knightsTale2+i);
    if (c) Serial.print(c,BYTE);
    i++;
  } while (c);
}
void loop() {
}
